// apps/shared/components/NeoCard.vue
<template>
  <div
    :class="['neo-card', `neo-card--${variant}`, { 'neo-card--hoverable': hoverable, 'neo-card--flat': flat }]"
    :role="hoverable ? 'button' : 'region'"
    :tabindex="hoverable ? 0 : undefined"
    :aria-label="ariaLabel || title || null"
    @click="hoverable && $emit('click', $event)"
    @keydown.enter="hoverable && $emit('click', createClickEvent($event))"
    @keydown.space.prevent="hoverable && $emit('click', createClickEvent($event))"
  >
    <div v-if="title || $slots.header" class="neo-card__header">
      <span v-if="title" class="neo-card__title">{{ title }}</span>
      <slot name="header" />
    </div>
    <div class="neo-card__body">
      <slot />
    </div>
    <div v-if="$slots.footer" class="neo-card__footer">
      <slot name="footer" />
    </div>
  </div>
</template>

<script setup lang="ts">
export type CardVariant =
  | "default"
  | "accent"
  | "success"
  | "warning"
  | "danger"
  | "erobo"
  | "erobo-neo"
  | "erobo-bitcoin";

withDefaults(
  defineProps<{
    title?: string;
    variant?: CardVariant;
    hoverable?: boolean;
    flat?: boolean;
    /** Accessibility label for screen readers */
    ariaLabel?: string;
  }>(),
  {
    title: undefined,
    variant: "default",
    hoverable: false,
    flat: false,
    ariaLabel: undefined,
  }
);

defineEmits<{
  (e: "click", event: MouseEvent): void;
}>();

function createClickEvent(keyboardEvent: KeyboardEvent): MouseEvent {
  return new MouseEvent("click", {
    bubbles: true,
    cancelable: true,
    view: keyboardEvent.view || window,
  });
}
</script>

<style lang="scss" scoped>
@use "../styles/tokens.scss" as *;

.neo-card {
  background: var(--bg-card, rgba(255, 255, 255, 0.02));
  border: 1px solid var(--border-color, rgba(255, 255, 255, 0.05));
  border-radius: var(--card-radius, 20px);
  box-shadow: 0 4px 20px var(--shadow-color, rgba(0, 0, 0, 0.1));
  overflow: hidden;
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
  color: var(--text-primary, #ffffff);

  &--flat {
    box-shadow: none;
    background: transparent;
    border: none;
    backdrop-filter: none;
  }

  &--hoverable {
    cursor: pointer;
    &:hover {
      transform: translateY(-4px);
      box-shadow: 0 20px 50px rgba(27, 27, 47, 0.18);
      border-color: rgba(159, 157, 243, 0.35);
      background: rgba(255, 255, 255, 0.08);
    }
    &:active {
      transform: translateY(-1px);
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    }
    &:focus-visible {
      outline: 2px solid var(--accent-primary, #3b82f6);
      outline-offset: 2px;
    }
  }

  // Variants with E-Robo Glass Gradients
  &--accent {
    background: linear-gradient(135deg, rgba(0, 229, 153, 0.1) 0%, rgba(0, 229, 153, 0.05) 100%);
    border-color: rgba(0, 229, 153, 0.3);
    box-shadow: 0 0 25px rgba(0, 229, 153, 0.15);
  }

  &--success {
    background: linear-gradient(135deg, rgba(16, 185, 129, 0.15) 0%, rgba(16, 185, 129, 0.05) 100%);
    border-color: rgba(16, 185, 129, 0.3);
    box-shadow: 0 0 25px rgba(16, 185, 129, 0.15);
  }

  &--warning {
    background: linear-gradient(135deg, rgba(253, 224, 71, 0.15) 0%, rgba(253, 224, 71, 0.05) 100%);
    border-color: rgba(253, 224, 71, 0.3);
    box-shadow: 0 0 25px rgba(253, 224, 71, 0.15);
  }

  &--danger {
    background: linear-gradient(135deg, rgba(239, 68, 68, 0.15) 0%, rgba(239, 68, 68, 0.05) 100%);
    border-color: rgba(239, 68, 68, 0.3);
    box-shadow: 0 0 25px rgba(239, 68, 68, 0.15);
  }

  // E-Robo Wallet Style Variants
  &--erobo {
    background: linear-gradient(135deg, rgba(159, 157, 243, 0.15) 0%, rgba(123, 121, 209, 0.08) 100%);
    border-color: rgba(159, 157, 243, 0.25);
    box-shadow: 0 0 30px rgba(159, 157, 243, 0.15);
    backdrop-filter: blur(50px);
    -webkit-backdrop-filter: blur(50px);

    &.neo-card--hoverable:hover {
      box-shadow: 0 0 40px rgba(159, 157, 243, 0.3);
      border-color: rgba(159, 157, 243, 0.4);
    }
  }

  &--erobo-neo {
    background: linear-gradient(135deg, rgba(0, 229, 153, 0.15) 0%, rgba(0, 179, 119, 0.08) 100%);
    border-color: rgba(0, 229, 153, 0.25);
    box-shadow: 0 0 30px rgba(0, 229, 153, 0.15);
    backdrop-filter: blur(50px);
    -webkit-backdrop-filter: blur(50px);

    &.neo-card--hoverable:hover {
      box-shadow: 0 0 40px rgba(0, 229, 153, 0.3);
      border-color: rgba(0, 229, 153, 0.4);
    }
  }

  &--erobo-bitcoin {
    background: linear-gradient(135deg, rgba(255, 228, 195, 0.15) 0%, rgba(255, 200, 140, 0.08) 100%);
    border-color: rgba(255, 228, 195, 0.25);
    box-shadow: 0 0 30px rgba(255, 228, 195, 0.15);
    backdrop-filter: blur(50px);
    -webkit-backdrop-filter: blur(50px);

    &.neo-card--hoverable:hover {
      box-shadow: 0 0 40px rgba(255, 228, 195, 0.3);
      border-color: rgba(255, 228, 195, 0.4);
    }
  }

  &__header {
    padding: 20px;
    border-bottom: 1px solid var(--border-color, rgba(255, 255, 255, 0.05));
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  &__title {
    font-size: 14px;
    font-weight: 700;
    color: var(--text-primary, rgba(255, 255, 255, 0.9));
    text-transform: uppercase;
    letter-spacing: 0.05em;
    font-family: $font-family;
  }

  &__body {
    padding: 20px;
  }

  &__footer {
    padding: 16px 20px;
    border-top: 1px solid var(--border-color, rgba(255, 255, 255, 0.05));
    background: var(--bg-secondary, rgba(0, 0, 0, 0.2));
  }
}

@media (prefers-reduced-motion: reduce) {
  .neo-card {
    transition: none;

    &--hoverable {
      &:hover {
        transform: none;
      }
      &:active {
        transform: none;
      }
    }
  }
}
</style>

// apps/shared/components-react/NeoCard.tsx
import { type ReactNode, type MouseEvent, type KeyboardEvent } from "react";
import "./NeoCard.scss";

export type CardVariant =
  | "default"
  | "accent"
  | "success"
  | "warning"
  | "danger"
  | "erobo"
  | "erobo-neo"
  | "erobo-bitcoin";

export interface NeoCardProps {
  title?: string;
  variant?: CardVariant;
  hoverable?: boolean;
  flat?: boolean;
  /** Accessibility label for screen readers */
  "aria-label"?: string;
  className?: string;
  children?: ReactNode;
  /** Content rendered inside the header alongside the title */
  header?: ReactNode;
  /** Content rendered in the footer section */
  footer?: ReactNode;
  onClick?: (event: MouseEvent<HTMLDivElement>) => void;
}

function createClickEvent(keyboardEvent: KeyboardEvent<HTMLDivElement>): MouseEvent<HTMLDivElement> {
  // Synthesize a MouseEvent from the keyboard event for the onClick handler
  return new window.MouseEvent("click", {
    bubbles: true,
    cancelable: true,
    view: window,
  }) as unknown as MouseEvent<HTMLDivElement>;
}

export function NeoCard({
  title,
  variant = "default",
  hoverable = false,
  flat = false,
  "aria-label": ariaLabel,
  className,
  children,
  header,
  footer,
  onClick,
}: NeoCardProps) {
  const classes = [
    "neo-card",
    `neo-card--${variant}`,
    hoverable && "neo-card--hoverable",
    flat && "neo-card--flat",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    if (!hoverable || !onClick) return;
    if (event.key === "Enter") {
      onClick(createClickEvent(event));
    } else if (event.key === " ") {
      event.preventDefault();
      onClick(createClickEvent(event));
    }
  }

  return (
    <div
      className={classes}
      role={hoverable ? "button" : "region"}
      tabIndex={hoverable ? 0 : undefined}
      aria-label={ariaLabel || title || undefined}
      onClick={hoverable ? onClick : undefined}
      onKeyDown={handleKeyDown}
    >
      {(title || header) && (
        <div className="neo-card__header">
          {title && <span className="neo-card__title">{title}</span>}
          {header}
        </div>
      )}
      <div className="neo-card__body">{children}</div>
      {footer && <div className="neo-card__footer">{footer}</div>}
    </div>
  );
}
