// apps/forever-album/src/components/AlbumGrid.tsx
import { NeoCard } from "@shared/components-react";
import "./AlbumGrid.scss";

interface PhotoItem {
  id: string;
  data: string;
  encrypted: boolean;
}

interface AlbumGridProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  photos: PhotoItem[];
  loading: boolean;
  onView: (photo: PhotoItem) => void;
  onUpload: () => void;
}

export default function AlbumGrid({ t, photos, loading, onView, onUpload }: AlbumGridProps) {
  return (
    <NeoCard variant="erobo" className="gallery-card">
      {loading ? (
        <div className="loading-state">
          <span>{t("loading")}</span>
        </div>
      ) : (
        <div className="gallery-grid">
          {photos.map((photo) => (
            <button
              key={photo.id}
              type="button"
              className="photo-item"
              aria-label={photo.encrypted ? t("encrypted") : t("albumPhoto")}
              onClick={() => onView(photo)}
            >
              {!photo.encrypted ? (
                <img src={photo.data} className="photo-img" alt={t("albumPhoto")} />
              ) : (
                <div className="photo-locked">
                  <span className="lock-label">{t("encrypted")}</span>
                </div>
              )}
              {photo.encrypted && (
                <div className="lock-icon" aria-hidden="true">{t("encrypted")}</div>
              )}
            </button>
          ))}

          <button
            type="button"
            className="photo-item placeholder"
            aria-label={t("addPhoto")}
            onClick={onUpload}
          >
            <span className="plus-icon" aria-hidden="true">+</span>
            <span className="add-label">{t("addPhoto")}</span>
          </button>
        </div>
      )}

      {!loading && photos.length === 0 && (
        <div className="empty-state">
          <span className="empty-title">{t("emptyTitle")}</span>
          <span className="empty-desc">{t("emptyDesc")}</span>
        </div>
      )}
    </NeoCard>
  );
}

// apps/forever-album/src/pages/index/components/AlbumGrid.vue
<template>
  <NeoCard variant="erobo" class="gallery-card">
    <div v-if="loading" class="loading-state">
      <span>{{ t("loading") }}</span>
    </div>
    <div v-else class="gallery-grid">
      <div
        v-for="photo in photos"
        :key="photo.id"
        class="photo-item"
        role="button"
        tabindex="0"
        :aria-label="photo.encrypted ? t('encrypted') : t('albumPhoto')"
        @click="$emit('view', photo)"
      >
        <img v-if="!photo.encrypted" :src="photo.data" mode="aspectFill" class="photo-img" :alt="t('albumPhoto')" />
        <div v-else class="photo-locked">
          <span class="lock-label">{{ t("encrypted") }}</span>
        </div>
        <div v-if="photo.encrypted" class="lock-icon" aria-hidden="true">{{ t("encrypted") }}</div>
      </div>

      <div
        class="photo-item placeholder"
        role="button"
        tabindex="0"
        :aria-label="t('addPhoto')"
        @click="$emit('upload')"
      >
        <span class="plus-icon" aria-hidden="true">+</span>
        <span class="add-label">{{ t("addPhoto") }}</span>
      </div>
    </div>

    <div v-if="!loading && photos.length === 0" class="empty-state">
      <span class="empty-title">{{ t("emptyTitle") }}</span>
      <span class="empty-desc">{{ t("emptyDesc") }}</span>
    </div>
  </NeoCard>
</template>

<script setup lang="ts">
import { NeoCard } from "@shared/components";
import { createUseI18n } from "@shared/composables";
import { messages } from "@/locale/messages";
import type { PhotoItem } from "@/types";

defineProps<{
  photos: PhotoItem[];
  loading: boolean;
}>();

const { t } = createUseI18n(messages)();

defineEmits<{
  (e: "view", photo: PhotoItem): void;
  (e: "upload"): void;
}>();
</script>

<style scoped lang="scss">
@use "@shared/styles/mixins.scss" as *;
.gallery-card {
  padding: 16px;
}
.gallery-grid {
  @include grid-layout(3, 12px);
}
.photo-item {
  aspect-ratio: 1 / 1;
  border-radius: 16px;
  overflow: hidden;
  position: relative;
  background: var(--bg-card);
  border: 1px solid var(--border-color);
}
.photo-img {
  width: 100%;
  height: 100%;
}
.photo-locked {
  width: 100%;
  height: 100%;
  background: var(--album-locked-gradient);
  display: flex;
  align-items: center;
  justify-content: center;
}
.lock-label {
  font-size: 11px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--album-lock-text);
}
.lock-icon {
  position: absolute;
  top: 6px;
  right: 6px;
  background: var(--album-lock-bg);
  padding: 2px 6px;
  border-radius: 8px;
  font-size: 9px;
  color: var(--album-lock-text);
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.placeholder {
  border: 1px dashed var(--border-color);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: transparent;
  gap: 6px;
}
.plus-icon {
  font-size: 32px;
  color: var(--text-secondary);
  font-weight: 300;
}
.add-label {
  font-size: 10px;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.12em;
}
.empty-state {
  margin-top: 14px;
  text-align: center;
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.empty-title {
  font-size: 13px;
  font-weight: 700;
}
.empty-desc {
  font-size: 11px;
  color: var(--text-muted);
}
.loading-state {
  text-align: center;
  font-size: 12px;
  color: var(--text-secondary);
}
</style>
