// apps/neo-x-bridge/src/components/BridgeActions.vue
<template>
  <div class="action-row">
    <NeoButton variant="primary" type="button" block @click="$emit('openBridge')">
      {{ t("officialBridge") }}
    </NeoButton>
    <NeoButton variant="secondary" type="button" block @click="$emit('addWallet')">
      {{ t("addWallet") }}
    </NeoButton>
    <NeoButton variant="secondary" type="button" block @click="$emit('openExplorer')">
      {{ t("openExplorer") }}
    </NeoButton>
    <NeoButton variant="secondary" type="button" block @click="$emit('openDocs')">
      {{ t("openDocs") }}
    </NeoButton>
  </div>
</template>

<script setup lang="ts">
import { NeoButton } from "@shared/components";

defineProps<{
  t: (key: string, params?: Record<string, string | number>) => string;
}>();

defineEmits<{
  openBridge: [];
  addWallet: [];
  openExplorer: [];
  openDocs: [];
}>();
</script>

<style lang="scss" scoped>
.action-row {
  display: flex;
  flex-direction: column;
  gap: 10px;
}
</style>

// apps/neo-x-bridge/src/components/BridgeActions.tsx
import { NeoButton } from "@shared/components-react";
import "./BridgeActions.scss";

interface BridgeActionsProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  onOpenBridge: () => void;
  onAddWallet: () => void;
  onOpenExplorer: () => void;
  onOpenDocs: () => void;
}

export default function BridgeActions({ t, onOpenBridge, onAddWallet, onOpenExplorer, onOpenDocs }: BridgeActionsProps) {
  return (
    <div className="action-row">
      <NeoButton variant="primary" block onClick={onOpenBridge}>
        {t("officialBridge")}
      </NeoButton>
      <NeoButton variant="secondary" block onClick={onAddWallet}>
        {t("addWallet")}
      </NeoButton>
      <NeoButton variant="secondary" block onClick={onOpenExplorer}>
        {t("openExplorer")}
      </NeoButton>
      <NeoButton variant="secondary" block onClick={onOpenDocs}>
        {t("openDocs")}
      </NeoButton>
    </div>
  );
}
