// apps/neoburger/src/components/SwapInterface.vue
<template>
  <div class="swap-panel">
    <div class="swap-block">
      <div class="swap-row">
        <span class="swap-label">{{ t("from") }}</span>
        <span class="swap-hint">
          {{ t("balance") }}:
          {{ formatAmount(swapMode === "stake" ? neoBalance : bNeoBalance) }}
          {{ swapMode === "stake" ? t("tokenNeo") : t("tokenBneo") }}
        </span>
      </div>
      <div class="swap-input">
        <div class="swap-asset">
          <img
            class="swap-asset-icon"
            :src="swapMode === 'stake' ? '/static/neoburger-neo-logo.svg' : '/static/neoburger-bneo-logo.svg'"
            mode="widthFix"
            :alt="swapMode === 'stake' ? t('neoAlt') : t('bneoAlt')"
          />
          <span class="swap-asset-label">{{ swapMode === "stake" ? t("tokenNeo") : t("tokenBneo") }}</span>
        </div>
        <NeoInput
          :modelValue="swapAmount"
          @update:modelValue="emit('update:swapAmount', $event)"
          type="number"
          :placeholder="t('inputPlaceholder')"
          class="swap-input-field"
        />
      </div>
      <span class="swap-usd">{{ swapUsdText }}</span>
    </div>

    <button type="button" class="swap-toggle" :aria-label="t('swapToggleAlt')" @click="emit('toggleMode')">
      <img
        class="swap-toggle-icon"
        src="/static/neoburger-placeholder.svg"
        mode="widthFix"
        :alt="t('swapToggleAlt')"
      />
    </button>

    <div class="swap-block">
      <div class="swap-row">
        <span class="swap-label">{{ t("to") }}</span>
        <span class="swap-hint">{{ t("estimatedOutput") }}</span>
      </div>
      <div class="swap-output">
        <div class="swap-asset">
          <img
            class="swap-asset-icon"
            :src="swapMode === 'stake' ? '/static/neoburger-bneo-logo.svg' : '/static/neoburger-neo-logo.svg'"
            mode="widthFix"
            :alt="swapMode === 'stake' ? t('bneoAlt') : t('neoAlt')"
          />
          <span class="swap-asset-label">{{ swapMode === "stake" ? t("tokenBneo") : t("tokenNeo") }}</span>
        </div>
        <span class="swap-output-value">{{ swapOutput }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { createUseI18n } from "@shared/composables/useI18n";
import { messages } from "@/locale/messages";
import { NeoInput } from "@shared/components";

const { t } = createUseI18n(messages)();

defineProps<{
  swapMode: "stake" | "unstake";
  neoBalance: number;
  bNeoBalance: number;
  swapAmount: string;
  swapOutput: string;
  swapUsdText: string;
}>();

const emit = defineEmits<{
  (e: "update:swapAmount", value: string): void;
  (e: "toggleMode"): void;
}>();

function formatAmount(amount: number): string {
  return amount.toFixed(2);
}
</script>

<style lang="scss" scoped>
.swap-panel {
  display: grid;
  gap: 14px;
}

.swap-block {
  background: var(--burger-surface-alt);
  border-radius: 18px;
  border: 1px solid var(--burger-border);
  padding: 14px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.swap-row {
  display: flex;
  justify-content: space-between;
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--burger-text-muted);
  font-weight: 700;
}

.swap-input {
  display: flex;
  align-items: center;
  gap: 12px;
}

.swap-asset {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 6px 10px;
  border-radius: 999px;
  background: var(--burger-surface);
  border: 1px solid var(--burger-border);
  font-weight: 700;
  font-size: 12px;
}

.swap-asset-icon {
  width: 18px;
}

.swap-input-field {
  flex: 1;
  min-width: 0;
}

.swap-usd {
  font-size: 12px;
  color: var(--burger-text-muted);
}

.swap-toggle {
  align-self: center;
  width: 44px;
  height: 44px;
  border-radius: 50%;
  border: none;
  background: var(--burger-accent);
  box-shadow: var(--burger-accent-shadow-soft);
  display: grid;
  place-items: center;
  cursor: pointer;
}

.swap-toggle-icon {
  width: 18px;
}

.swap-output {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 12px;
  border-radius: 14px;
  background: var(--burger-surface);
  border: 1px dashed var(--burger-border-dashed);
}

.swap-output-value {
  font-weight: 700;
  font-size: 16px;
}
</style>

// apps/neoburger/src/components/SwapInterface.tsx
import type { Observable } from "@shared/react/context";
import { NeoInput, NeoButton } from "@shared/components-react";
import "./SwapInterface.scss";

interface SwapInterfaceProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  swapMode: string;
  neoBalance: number;
  bNeoBalance: number;
  swapAmount: string;
  swapOutput: string;
  swapUsdText: string;
  state: Record<string, Observable>;
}

export default function SwapInterface({ t, swapMode, neoBalance, bNeoBalance, swapAmount, swapOutput, swapUsdText, state }: SwapInterfaceProps) {
  const updateAmount = (val: string) => { if (state.swapAmount) state.swapAmount.set(val); };
  const toggleMode = () => {
    if (state.swapMode) {
      const current = state.swapMode.get() as string;
      state.swapMode.set(current === "stake" ? "unstake" : "stake");
    }
  };

  const formatAmount = (n: number | null) => n != null ? n.toFixed(4) : "-";

  return (
    <div className="swap-panel">
      <div className="swap-block">
        <div className="swap-row">
          <span className="swap-label">{t("from")}</span>
          <span className="swap-hint">
            {t("balance")}: {formatAmount(swapMode === "stake" ? neoBalance : bNeoBalance)} {swapMode === "stake" ? t("tokenNeo") : t("tokenBneo")}
          </span>
        </div>
        <NeoInput value={swapAmount} type="number" placeholder={t("inputPlaceholder")} onChange={updateAmount} />
        <span className="swap-usd">{swapUsdText}</span>
      </div>

      <NeoButton variant="secondary" onClick={toggleMode} aria-label={t("swapToggleAlt")}>
        {swapMode === "stake" ? t("swapToBneo") : t("swapToNeo")}
      </NeoButton>

      <div className="swap-block">
        <div className="swap-row">
          <span className="swap-label">{t("to")}</span>
          <span className="swap-hint">{t("estimatedOutput")}</span>
        </div>
        <div className="swap-output-value">{swapOutput || "0"}</div>
      </div>
    </div>
  );
}
