// apps/time-capsule/src/components/CapsuleList.tsx
import "./CapsuleList.scss";

interface CapsuleListProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  totalCapsules: number;
}

export default function CapsuleList({ t, totalCapsules }: CapsuleListProps) {
  return (
    <div className="capsule-list-container">
      {totalCapsules === 0 && (
        <div className="empty-state">
          <span>{t("noCapsules")}</span>
        </div>
      )}
    </div>
  );
}

// apps/time-capsule/src/components/CapsuleList.vue
<template>
  <div class="capsule-list-container">
    <div v-if="totalCapsules === 0" class="empty-state">
      <span>{{ t("noCapsules", { fallback: "No capsules yet" }) }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  t: (key: string, params?: Record<string, string | number>) => string;
  totalCapsules: number;
}>();
</script>

<style lang="scss" scoped>
.empty-state {
  text-align: center;
  padding: 24px;
  color: rgba(255, 255, 255, 0.4);
  font-size: 14px;
}
</style>
