// apps/last-survivor/src/components/DangerMeter.tsx
import "./DangerMeter.scss";

interface DangerMeterProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  level: string;
  levelText: string;
  progress: number;
}

export default function DangerMeter({ t, level, levelText, progress }: DangerMeterProps) {
  return (
    <div className="danger-meter">
      <div className="meter-header">
        <span className="meter-label-left">{t("safe")}</span>
        <div className={`danger-badge ${level}`}><span>{levelText}</span></div>
        <span className="meter-label-right">{t("critical")}</span>
      </div>
      <div className="meter-track">
        <div className="meter-gradient-bg" />
        <div className={`meter-fill ${level}`} style={{ width: `${progress}%` }} />
        <div className="meter-glow-point" style={{ left: `${progress}%` }} />
        <div className="zone-markers">
          <div className="zone-mark" style={{ left: "25%" }}><span className="zone-tick" /></div>
          <div className="zone-mark" style={{ left: "50%" }}><span className="zone-tick" /></div>
          <div className="zone-mark" style={{ left: "75%" }}><span className="zone-tick" /></div>
        </div>
      </div>
      <div className="meter-zone-labels">
        <span className="zone-label safe-label">SAFE</span>
        <span className="zone-label warn-label">WARN</span>
        <span className="zone-label high-label">HIGH</span>
        <span className="zone-label crit-label">CRIT</span>
      </div>
    </div>
  );
}

// apps/last-survivor/src/components/DangerMeter.vue
<template>
  <div class="danger-meter">
    <div class="meter-header">
      <span class="meter-label-left">{{ t("safe") }}</span>
      <div :class="['danger-badge', level]">
        <span>{{ levelText }}</span>
      </div>
      <span class="meter-label-right">{{ t("critical") }}</span>
    </div>
    <div class="meter-track">
      <div class="meter-gradient-bg" />
      <div :class="['meter-fill', level]" :style="{ width: progress + '%' }" />
      <div class="meter-glow-point" :style="{ left: progress + '%' }" />
      <!-- Zone markers -->
      <div class="zone-markers">
        <div class="zone-mark" style="left: 25%"><span class="zone-tick" /></div>
        <div class="zone-mark" style="left: 50%"><span class="zone-tick" /></div>
        <div class="zone-mark" style="left: 75%"><span class="zone-tick" /></div>
      </div>
    </div>
    <div class="meter-zone-labels">
      <span class="zone-label safe-label">SAFE</span>
      <span class="zone-label warn-label">WARN</span>
      <span class="zone-label high-label">HIGH</span>
      <span class="zone-label crit-label">CRIT</span>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  t: (key: string, params?: Record<string, string | number>) => string;
  level: string;
  levelText: string;
  progress: number;
}>();
</script>

<style lang="scss" scoped>
@use "@shared/styles/tokens.scss" as *;
@use "@shared/styles/variables.scss" as *;

.danger-meter {
  width: 100%;
  max-width: 320px;
}

.meter-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}

.meter-label-left,
.meter-label-right {
  font-size: 9px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--text-tertiary, rgba(255, 255, 255, 0.3));
}

.danger-badge {
  padding: 2px 10px;
  border-radius: 20px;
  font-size: 9px;
  font-weight: 900;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  border: 1px solid var(--border-subtle, rgba(255, 255, 255, 0.15));
  backdrop-filter: blur(4px);

  &.low { background: rgba(16, 185, 129, 0.2); color: var(--doom-safe, var(--accent-success, #34d399)); }
  &.medium { background: rgba(245, 158, 11, 0.2); color: var(--doom-warn-light, var(--accent-warning, #fbbf24)); }
  &.high { background: rgba(239, 68, 68, 0.2); color: var(--doom-danger-light, var(--accent-error, #f87171)); }
  &.critical {
    background: rgba(239, 68, 68, 0.3);
    color: var(--doom-danger-light, var(--accent-error, #f87171));
    box-shadow: 0 0 8px rgba(239, 68, 68, 0.4);
  }
}

.meter-track {
  height: 8px;
  background: var(--bg-elevated, rgba(0, 0, 0, 0.4));
  border-radius: 4px;
  position: relative;
  overflow: visible;
  border: 1px solid var(--border-subtle, rgba(255, 255, 255, 0.06));
}

.meter-gradient-bg {
  position: absolute;
  inset: 0;
  border-radius: 4px;
  background: linear-gradient(90deg,
    rgba(16, 185, 129, 0.1) 0%,
    rgba(245, 158, 11, 0.1) 33%,
    rgba(239, 68, 68, 0.1) 66%,
    rgba(220, 38, 38, 0.15) 100%
  );
}

.meter-fill {
  height: 100%;
  border-radius: 4px;
  transition: width 0.8s cubic-bezier(0.4, 0, 0.2, 1), background 0.5s ease;
  position: relative;
  z-index: 1;

  &.low {
    background: linear-gradient(90deg, var(--doom-green, #10b981), var(--doom-success, #34d399));
  }
  &.medium {
    background: linear-gradient(90deg, var(--doom-green, #10b981), var(--doom-amber, #f59e0b), var(--doom-warn-light, #fbbf24));
  }
  &.high {
    background: linear-gradient(90deg, var(--doom-green, #10b981), var(--doom-amber, #f59e0b), var(--doom-red, #ef4444));
    box-shadow: 0 0 6px rgba(239, 68, 68, 0.3);
  }
  &.critical {
    background: linear-gradient(90deg, var(--doom-green, #10b981), var(--doom-amber, #f59e0b), var(--doom-red, #ef4444), var(--doom-red-deep, #dc2626));
    box-shadow: 0 0 12px rgba(239, 68, 68, 0.5);
    animation: critical-flash 1s ease-in-out infinite alternate;
  }
}

.meter-glow-point {
  position: absolute;
  top: 50%;
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: var(--doom-white, var(--text-primary, #fff));
  transform: translate(-50%, -50%);
  box-shadow: 0 0 8px var(--doom-white, rgba(255, 255, 255, 0.8));
  transition: left 0.8s cubic-bezier(0.4, 0, 0.2, 1);
  z-index: 2;
  border: 2px solid rgba(0, 0, 0, 0.3);
}

.zone-markers {
  position: absolute;
  inset: 0;
  z-index: 1;
}

.zone-mark {
  position: absolute;
  top: -3px;
  bottom: -3px;
  width: 1px;
}

.zone-tick {
  display: block;
  width: 1px;
  height: 100%;
  background: rgba(255, 255, 255, 0.15);
}

.meter-zone-labels {
  display: flex;
  justify-content: space-between;
  margin-top: 4px;
  padding: 0 2px;
}

.zone-label {
  font-size: 7px;
  font-weight: 900;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  flex: 1;
  text-align: center;

  &.safe-label { color: rgba(16, 185, 129, 0.5); }
  &.warn-label { color: rgba(245, 158, 11, 0.5); }
  &.high-label { color: rgba(239, 68, 68, 0.4); }
  &.crit-label { color: rgba(220, 38, 38, 0.5); }
}

@keyframes critical-flash {
  0% { box-shadow: 0 0 8px rgba(239, 68, 68, 0.3); }
  100% { box-shadow: 0 0 18px rgba(239, 68, 68, 0.6); }
}
</style>
