// apps/fogplay/src/pages/index/components/BetControls.tsx
import { NeoButton } from "@shared/components-react";
import "./BetControls.scss";

interface BetControlsProps {
  choice: "heads" | "tails";
  betAmount: string;
  isFlipping: boolean;
  canBet: boolean;
  t: (key: string, params?: Record<string, string | number>) => string;
  onChoiceChange: (side: "heads" | "tails") => void;
  onBetAmountChange: (amount: string) => void;
  onFlip: () => void;
}

export default function BetControls({ choice, betAmount, isFlipping, canBet, t, onChoiceChange, onBetAmountChange, onFlip }: BetControlsProps) {
  return (
    <div className="premium-controls">
      <div className="choice-grid">
        {(["heads", "tails"] as const).map((side) => (
          <div key={side} className={`choice-card ${choice === side ? side : "inactive"}`} onClick={() => onChoiceChange(side)}>
            <div className="card-inner">
              <div className="symbol-ring">{side === "heads" ? <div className="neo-symbol">N</div> : <div className="gas-symbol">G</div>}</div>
              <span className="choice-name">{t(side)}</span>
            </div>
          </div>
        ))}
      </div>
      <div className="wager-panel">
        <div className="panel-header"><span className="label">{t("wager")}</span></div>
        <div className="wager-grid">
          {["1", "5", "10", "50"].map((amount) => (
            <div key={amount} className={`wager-option${betAmount === amount ? " selected" : ""}`} onClick={() => onBetAmountChange(amount)}>
              <span className="amount-val">{amount}</span><span className="amount-unit">{t("tokenGas")}</span>
            </div>
          ))}
        </div>
        <div className="action-zone">
          <NeoButton variant="primary" size="lg" block disabled={isFlipping || !canBet} loading={isFlipping} onClick={onFlip} className="premium-flip-btn" aria-label={isFlipping ? t("flipping") : t("flipCoin")}>
            <div className="btn-content"><span>{isFlipping ? t("flipping") : t("flipCoin")}</span></div>
          </NeoButton>
        </div>
      </div>
    </div>
  );
}

// apps/fogplay/src/pages/index/components/BetControls.vue
<template>
  <div class="premium-controls">
    <div class="choice-grid">
      <div
        v-for="side in ['heads', 'tails']"
        :key="side"
        :class="['choice-card', choice === side ? side : 'inactive']"
        @click="$emit('update:choice', side)"
      >
        <div class="card-glow" />
        <div class="card-inner">
          <div class="symbol-ring">
            <div v-if="side === 'heads'" class="neo-symbol">N</div>
            <div v-else class="gas-symbol">G</div>
          </div>
          <span class="choice-name">{{ t(side) }}</span>
        </div>
      </div>
    </div>

    <div class="wager-panel">
      <div class="panel-header">
        <span class="label">{{ t("wager") }}</span>
        <div class="balance-pill">
          <span class="val">{{ t("wagerRange") }}</span>
          <span class="unit">{{ t("tokenGas") }}</span>
        </div>
      </div>

      <div class="wager-grid">
        <div
          v-for="amount in ['1', '5', '10', '50']"
          :key="amount"
          :class="['wager-option', betAmount === amount ? 'selected' : '']"
          @click="$emit('update:betAmount', amount)"
        >
          <span class="amount-val">{{ amount }}</span>
          <span class="amount-unit">{{ t("tokenGas") }}</span>
        </div>
      </div>

      <div class="action-zone">
        <div class="flip-button-wrapper">
          <NeoButton
            variant="primary"
            size="lg"
            block
            type="button"
            :disabled="isFlipping || !canBet"
            :loading="isFlipping"
            @click="$emit('flip')"
            class="premium-flip-btn"
            :aria-label="isFlipping ? t('flipping') : t('flipCoin')"
          >
            <div class="btn-content">
              <span v-if="!isFlipping">{{ t("flipCoin") }}</span>
              <span v-else>{{ t("flipping") }}</span>
            </div>
          </NeoButton>
          <div class="btn-shadow" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { NeoButton } from "@shared/components";
import { createUseI18n } from "@shared/composables/useI18n";
import { messages } from "@/locale/messages";

const { t } = createUseI18n(messages)();

defineProps<{
  choice: "heads" | "tails";
  betAmount: string;
  isFlipping: boolean;
  canBet: boolean;
}>();

defineEmits<{
  (e: "update:choice", side: "heads" | "tails"): void;
  (e: "update:betAmount", amount: string): void;
  (e: "flip"): void;
}>();
</script>

<style lang="scss" scoped>
@use "@shared/styles/mixins.scss" as *;

.premium-controls {
  display: flex;
  flex-direction: column;
  gap: 32px;
  width: 100%;
}

.choice-grid {
  @include grid-layout(2, 20px);
}

.choice-card {
  position: relative;
  height: 140px;
  background: var(--coin-choice-bg);
  border: 1px solid var(--coin-choice-border);
  border-radius: 24px;
  overflow: hidden;
  transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
  cursor: pointer;

  .card-inner {
    position: relative;
    z-index: 2;
    height: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 12px;
  }

  .symbol-ring {
    width: 60px;
    height: 60px;
    border-radius: 50%;
    border: 2px solid var(--coin-choice-ring);
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 900;
    font-size: 24px;
    transition: all 0.3s ease;
  }

  &.heads.heads {
    background: linear-gradient(135deg, rgba(0, 229, 153, 0.2) 0%, rgba(0, 229, 153, 0.05) 100%);
    border-color: var(--coin-success);
    box-shadow: 0 10px 30px rgba(0, 229, 153, 0.2);
    transform: scale(1.05);
    .symbol-ring {
      border-color: var(--coin-success);
      color: var(--coin-success);
      box-shadow: 0 0 15px rgba(0, 229, 153, 0.3);
    }
    .choice-name {
      color: var(--coin-success);
      text-shadow: 0 0 10px rgba(0, 229, 153, 0.5);
    }
  }

  &.tails.tails {
    background: linear-gradient(135deg, rgba(59, 130, 246, 0.2) 0%, rgba(59, 130, 246, 0.05) 100%);
    border-color: var(--coin-blue);
    box-shadow: 0 10px 30px rgba(59, 130, 246, 0.2);
    transform: scale(1.05);
    .symbol-ring {
      border-color: var(--coin-blue);
      color: var(--coin-blue);
      box-shadow: 0 0 15px rgba(59, 130, 246, 0.3);
    }
    .choice-name {
      color: var(--coin-blue);
      text-shadow: 0 0 10px rgba(59, 130, 246, 0.5);
    }
  }

  &.inactive {
    opacity: 0.6;
    &:hover {
      opacity: 1;
      transform: translateY(-4px);
    }
  }
}

.choice-name {
  font-size: 14px;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 2px;
  color: var(--coin-text-primary);
}

.wager-panel {
  background: var(--coin-panel-bg);
  padding: 24px;
  border-radius: 24px;
  border: 1px solid var(--coin-panel-border);
}

.panel-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;

  .label {
    font-size: 12px;
    font-weight: 700;
    color: var(--coin-label);
    text-transform: uppercase;
    letter-spacing: 1px;
  }
}

.balance-pill {
  background: rgba(0, 229, 153, 0.1);
  padding: 4px 12px;
  border-radius: 99px;
  font-size: 11px;
  font-weight: 700;
  color: var(--coin-success);
  border: 1px solid rgba(0, 229, 153, 0.2);
  .unit {
    opacity: 0.7;
    margin-left: 4px;
  }
}

.wager-grid {
  @include grid-layout(4, 12px);
  margin-bottom: 32px;
}

.wager-option {
  background: var(--coin-wager-bg);
  border: 1px solid var(--coin-wager-border);
  padding: 16px 8px;
  border-radius: 16px;
  text-align: center;
  transition: all 0.3s ease;

  .amount-val {
    display: block;
    font-size: 18px;
    font-weight: 800;
    color: var(--coin-text-primary);
  }
  .amount-unit {
    font-size: 9px;
    opacity: 0.6;
    color: var(--coin-text-secondary);
    text-transform: uppercase;
  }

  &.selected {
    background: var(--coin-success);
    border-color: var(--coin-success);
    box-shadow: 0 0 20px rgba(0, 229, 153, 0.4);
    .amount-val,
    .amount-unit {
      color: var(--coin-black);
    }
  }
}

.flip-button-wrapper {
  position: relative;

  .premium-flip-btn {
    height: 64px;
    font-size: 18px;
    font-weight: 900;
    text-transform: uppercase;
    letter-spacing: 2px;
    border-radius: 16px;
    background: var(--flip-cta-gradient);
    box-shadow: 0 10px 30px rgba(0, 229, 153, 0.3);
    border: none;
    z-index: 2;
  }

  .btn-shadow {
    position: absolute;
    bottom: -6px;
    left: 4px;
    right: 4px;
    height: 20px;
    background: var(--coin-btn-shadow);
    border-radius: 16px;
    z-index: 1;
  }

  &:active .premium-flip-btn {
    transform: translateY(4px);
    box-shadow: 0 4px 15px rgba(0, 229, 153, 0.2);
  }
}
</style>
