// apps/daily-checkin/src/pages/index/components/StreakDisplay.vue
<template>
  <NeoCard variant="erobo" class="streak-card pt-6 pb-6 text-center">
    <div class="streak-flames">
      <span v-for="i in Math.min(currentStreak, 7)" :key="i" class="flame">🔥</span>
      <span v-if="currentStreak === 0" class="flame-empty">💤</span>
    </div>
    <span class="streak-count">{{ currentStreak }} {{ t("dayStreak") }}</span>
    <span class="streak-best">{{ t("bestStreak") }}: {{ highestStreak }} {{ t("days") }}</span>
  </NeoCard>
</template>

<script setup lang="ts">
import { NeoCard } from "@shared/components";
import { createUseI18n } from "@shared/composables/useI18n";
import { messages } from "@/locale/messages";

const { t } = createUseI18n(messages)();

defineProps<{
  currentStreak: number;
  highestStreak: number;
}>();
</script>

<style lang="scss" scoped>
@use "@shared/styles/tokens.scss" as *;
@use "@shared/styles/variables.scss" as *;



.streak-flames {
  font-size: 32px;
  margin-bottom: 16px;
  letter-spacing: 4px;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.flame-empty { opacity: 0.5; }

.streak-count {
  display: block;
  font-size: 24px;
  font-weight: 800;
  color: var(--text-primary);
  margin-bottom: 4px;
  font-family: $font-family;
  text-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
}

.streak-best {
  display: block;
  font-size: 13px;
  font-weight: 500;
  color: var(--text-secondary, rgba(255, 255, 255, 0.5));
}
</style>

// apps/daily-checkin/src/pages/index/components/StreakDisplay.tsx
import { NeoCard } from "@shared/components-react";
import "./StreakDisplay.scss";

interface StreakDisplayProps {
  currentStreak: number;
  highestStreak: number;
  t: (key: string, params?: Record<string, string | number>) => string;
}

export default function StreakDisplay({ currentStreak, highestStreak, t }: StreakDisplayProps) {
  return (
    <NeoCard variant="erobo" className="streak-card pt-6 pb-6 text-center">
      <div className="streak-flames">
        {currentStreak > 0
          ? Array.from({ length: Math.min(currentStreak, 7) }, (_, i) => (
              <span key={i} className="flame">{"\uD83D\uDD25"}</span>
            ))
          : <span className="flame-empty">{"\uD83D\uDCA4"}</span>}
      </div>
      <span className="streak-count">{currentStreak} {t("dayStreak")}</span>
      <span className="streak-best">{t("bestStreak")}: {highestStreak} {t("days")}</span>
    </NeoCard>
  );
}
