// apps/daily-checkin/src/pages/index/components/UserRewards.tsx
import { NeoCard, NeoButton } from "@shared/components-react";
import { formatGas } from "@shared/utils/format";
import "./UserRewards.scss";

interface UserRewardsProps {
  unclaimedRewards: number;
  totalClaimed: number;
  isClaiming: boolean;
  t: (key: string, params?: Record<string, string | number>) => string;
  onClaim: () => void;
}

export default function UserRewards({ unclaimedRewards, totalClaimed, isClaiming, t, onClaim }: UserRewardsProps) {
  return (
    <NeoCard variant="erobo" className="mt-4">
      <div className="rewards-grid">
        <div className="reward-item">
          <span className="reward-value">{formatGas(unclaimedRewards)}</span>
          <span className="reward-label">{t("unclaimed")}</span>
        </div>
        <div className="reward-item">
          <span className="reward-value">{formatGas(totalClaimed)}</span>
          <span className="reward-label">{t("totalClaimed")}</span>
        </div>
      </div>
      {unclaimedRewards > 0 && (
        <NeoButton
          variant="success"
          size="md"
          block
          loading={isClaiming}
          onClick={onClaim}
          className="mt-4"
        >
          {t("claimRewards")} ({formatGas(unclaimedRewards)} {t("tokenGas")})
        </NeoButton>
      )}
    </NeoCard>
  );
}

// apps/daily-checkin/src/pages/index/components/UserRewards.vue
<template>
  <NeoCard variant="erobo" class="mt-4">
    <div class="rewards-grid">
      <div class="reward-item">
        <span class="reward-value">{{ formatGas(unclaimedRewards) }}</span>
        <span class="reward-label">{{ t("unclaimed") }}</span>
      </div>
      <div class="reward-item">
        <span class="reward-value">{{ formatGas(totalClaimed) }}</span>
        <span class="reward-label">{{ t("totalClaimed") }}</span>
      </div>
    </div>
    <NeoButton
      v-if="unclaimedRewards > 0"
      variant="success"
      size="md"
      block
      type="button"
      :loading="isClaiming"
      @click="$emit('claim')"
      class="mt-4"
    >
      {{ t("claimRewards") }} ({{ formatGas(unclaimedRewards) }} {{ t("tokenGas") }})
    </NeoButton>
  </NeoCard>
</template>

<script setup lang="ts">
import { NeoCard, NeoButton } from "@shared/components";
import { formatGas } from "@shared/utils/format";
import { createUseI18n } from "@shared/composables/useI18n";
import { messages } from "@/locale/messages";

const { t } = createUseI18n(messages)();

defineProps<{
  unclaimedRewards: number;
  totalClaimed: number;
  isClaiming: boolean;
}>();

defineEmits<{
  (e: "claim"): void;
}>();
</script>

<style lang="scss" scoped>
@use "@shared/styles/tokens.scss" as *;
@use "@shared/styles/variables.scss" as *;
@use "@shared/styles/mixins.scss" as *;

.rewards-grid {
  @include grid-layout(2, 16px);
}

.reward-item {
  @include card-base(12px, 16px);
  text-align: center;
}

.reward-value {
  @include stat-value;
  font-size: 24px;
  color: var(--sunrise-reward);
  text-shadow: 0 0 10px rgba(0, 229, 153, 0.3);
  margin-bottom: 4px;
}

.reward-label {
  @include stat-label;
  display: block;
  font-weight: 600;
}
</style>
