// apps/aa-market-hub/src/components/CreateListingCard.vue
<template>
  <NeoCard variant="erobo" :title="t('createListingTitle')" class="operation-card">
    <div class="stack">
      <NeoInput
        :modelValue="aaContractHash"
        @update:modelValue="aaContractHash = $event"
        :label="t('aaContractInput')"
        :hint="t('aaContractHint')"
        :placeholder="t('aaContractHashPlaceholder')"
      />
      <NeoInput
        :modelValue="accountIdHash"
        @update:modelValue="accountIdHash = $event"
        :label="t('accountIdInput')"
        :hint="t('accountIdHint')"
        :placeholder="t('accountIdHashPlaceholder')"
      />
      <NeoInput :modelValue="priceGas" @update:modelValue="priceGas = $event" :label="t('priceInput')" :placeholder="t('pricePlaceholder')" />
      <NeoInput :modelValue="listingTitle" @update:modelValue="listingTitle = $event" :label="t('titleInput')" :placeholder="t('titlePlaceholder')" />
      <NeoInput
        :modelValue="metadataUri"
        @update:modelValue="metadataUri = $event"
        type="textarea"
        :label="t('metadataInput')"
        :placeholder="t('metadataPlaceholder')"
      />
      <NeoButton variant="primary" type="button" :loading="isSubmitting" :disabled="!canCreateListing" @click="handleCreate" :aria-label="t('createListingCta')">
        {{ t("createListingCta") }}
      </NeoButton>
    </div>
  </NeoCard>
</template>

<script setup lang="ts">
import { ref, inject } from "vue";
import { NeoButton, NeoCard, NeoInput } from "@shared/components";
import { MINIAPP_ACTIONS_KEY } from "@shared/utils/defineMiniApp";

defineProps<{
  t: (key: string, params?: Record<string, string | number>) => string;
  isSubmitting: boolean;
  canCreateListing: boolean;
}>();

const actions = inject(MINIAPP_ACTIONS_KEY, new Map());

const aaContractHash = ref("");
const accountIdHash = ref("");
const priceGas = ref("");
const listingTitle = ref("");
const metadataUri = ref("");

const handleCreate = async () => {
  const handler = actions.get("createListing");
  if (handler) {
    await handler(
      aaContractHash.value,
      accountIdHash.value,
      priceGas.value,
      listingTitle.value,
      metadataUri.value,
    );
    accountIdHash.value = "";
    priceGas.value = "";
    listingTitle.value = "";
    metadataUri.value = "";
  }
};
</script>

<style scoped>
.stack {
  display: flex;
  flex-direction: column;
  gap: 14px;
}
</style>

// apps/aa-market-hub/src/components/CreateListingCard.tsx
import { useState } from "react";
import { NeoButton, NeoCard, NeoInput } from "@shared/components-react";

interface CreateListingCardProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  isSubmitting: boolean;
  canCreateListing: boolean;
  dispatch: (name: string, ...args: unknown[]) => Promise<void>;
}

export function CreateListingCard({ t, isSubmitting, canCreateListing, dispatch }: CreateListingCardProps) {
  const [aaContractHash, setAaContractHash] = useState("");
  const [accountIdHash, setAccountIdHash] = useState("");
  const [priceGas, setPriceGas] = useState("");
  const [listingTitle, setListingTitle] = useState("");
  const [metadataUri, setMetadataUri] = useState("");

  const handleCreate = async () => {
    await dispatch("createListing", aaContractHash, accountIdHash, priceGas, listingTitle, metadataUri);
    setAccountIdHash("");
    setPriceGas("");
    setListingTitle("");
    setMetadataUri("");
  };

  return (
    <NeoCard variant="erobo" title={t("createListingTitle")} className="operation-card">
      <div className="stack">
        <NeoInput value={aaContractHash} label={t("aaContractInput")} hint={t("aaContractHint")} placeholder={t("aaContractHashPlaceholder")} onChange={(val) => setAaContractHash(val)} />
        <NeoInput value={accountIdHash} label={t("accountIdInput")} hint={t("accountIdHint")} placeholder={t("accountIdHashPlaceholder")} onChange={(val) => setAccountIdHash(val)} />
        <NeoInput value={priceGas} label={t("priceInput")} placeholder={t("pricePlaceholder")} onChange={(val) => setPriceGas(val)} />
        <NeoInput value={listingTitle} label={t("titleInput")} placeholder={t("titlePlaceholder")} onChange={(val) => setListingTitle(val)} />
        <NeoInput value={metadataUri} type="textarea" label={t("metadataInput")} placeholder={t("metadataPlaceholder")} onChange={(val) => setMetadataUri(val)} />
        <NeoButton variant="primary" loading={isSubmitting} disabled={!canCreateListing} aria-label={t("createListingCta")} onClick={handleCreate}>
          {t("createListingCta")}
        </NeoButton>
      </div>
    </NeoCard>
  );
}
