// apps/aa-market-hub/src/components/WalletConnectCard.vue
<template>
  <NeoCard variant="erobo" :title="t('walletAndMarket')" class="operation-card">
    <div class="stack">
      <NeoInput :modelValue="modelValue" @update:modelValue="$emit('update:modelValue', $event)" :label="t('marketHash')" :placeholder="t('marketHashPlaceholder')" />
      <NeoButton variant="secondary" type="button" :loading="isWalletConnecting" @click="handleConnect" :aria-label="walletAddress ? t('walletConnected') : t('connectWallet')">
        {{ walletAddress ? t("walletConnected") : t("connectWallet") }}
      </NeoButton>
      <NeoButton variant="primary" type="button" :loading="isLoading" @click="$emit('loadListings')" :aria-label="t('loadListings')">{{ t("loadListings") }}</NeoButton>
    </div>
  </NeoCard>
</template>

<script setup lang="ts">
import { inject } from "vue";
import { NeoButton, NeoCard, NeoInput } from "@shared/components";
import { MINIAPP_ACTIONS_KEY } from "@shared/utils/defineMiniApp";

defineProps<{
  t: (key: string, params?: Record<string, string | number>) => string;
  modelValue: string;
  walletAddress: string;
  isWalletConnecting: boolean;
  isLoading: boolean;
}>();

defineEmits<{
  "update:modelValue": [value: string];
  loadListings: [];
}>();

const actions = inject(MINIAPP_ACTIONS_KEY, new Map());

const handleConnect = async () => {
  const handler = actions.get("connectWallet");
  if (handler) await handler();
};
</script>

<style scoped>
.stack {
  display: flex;
  flex-direction: column;
  gap: 14px;
}
</style>

// apps/aa-market-hub/src/components/WalletConnectCard.tsx
import { NeoButton, NeoCard, NeoInput } from "@shared/components-react";

interface WalletConnectCardProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  marketHash: string;
  walletAddress: string;
  isWalletConnecting: boolean;
  isLoading: boolean;
  canLoadListings: boolean;
  onMarketHashChange: (value: string) => void;
  onConnect: () => void;
  onLoadListings: () => void;
}

export function WalletConnectCard({
  t,
  marketHash,
  walletAddress,
  isWalletConnecting,
  isLoading,
  canLoadListings,
  onMarketHashChange,
  onConnect,
  onLoadListings,
}: WalletConnectCardProps) {
  return (
    <NeoCard
      variant="erobo"
      title={t("walletAndMarket")}
      className="operation-card"
    >
      <div className="stack market-command__body">
        <div className="market-command__status">
          <span>{t("walletLabel")}</span>
          <strong>{walletAddress || t("notConnected")}</strong>
        </div>
        <NeoInput
          value={marketHash}
          label={t("marketHash")}
          hint={t("marketHashHint")}
          placeholder={t("marketHashPlaceholder")}
          onChange={onMarketHashChange}
        />
        <div className="market-command__actions">
          <NeoButton
            variant="secondary"
            loading={isWalletConnecting}
            aria-label={
              walletAddress ? t("walletConnected") : t("connectWallet")
            }
            onClick={onConnect}
          >
            {walletAddress ? t("walletConnected") : t("connectWallet")}
          </NeoButton>
          <NeoButton
            variant="primary"
            loading={isLoading}
            disabled={!canLoadListings}
            aria-label={t("loadListings")}
            onClick={onLoadListings}
          >
            {t("loadListings")}
          </NeoButton>
        </div>
      </div>
    </NeoCard>
  );
}
