// apps/neo-multisig/src/components/MainCard.tsx
import { NeoInput, NeoButton } from "@shared/components-react";
import CreateCard from "./CreateCard";
import LoadSection from "./LoadSection";

interface MainCardProps {
  value: string; onChange: (val: string) => void; createTitle: string; createDesc: string;
  dividerText: string; loadLabel: string; loadPlaceholder: string; loadButtonText: string;
  onCreate: () => void; onLoad: () => void;
}

export default function MainCard({ value, onChange, createTitle, createDesc, dividerText, loadLabel, loadPlaceholder, loadButtonText, onCreate, onLoad }: MainCardProps) {
  return (
    <div className="main-card">
      <CreateCard title={createTitle} description={createDesc} onCreate={onCreate} />
      <div className="divider"><div className="divider-line" /><span className="divider-text">{dividerText}</span><div className="divider-line" /></div>
      <LoadSection value={value} onChange={onChange} label={loadLabel} placeholder={loadPlaceholder} buttonText={loadButtonText} onLoad={onLoad} />
    </div>
  );
}

// apps/neo-multisig/src/components/MainCard.vue
<template>
  <div class="main-card">
    <CreateCard :title="createTitle" :description="createDesc" @create="$emit('create')" />

    <div class="divider">
      <div class="divider-line"></div>
      <span class="divider-text">{{ dividerText }}</span>
      <div class="divider-line"></div>
    </div>

    <LoadSection
      v-model="inputValue"
      :label="loadLabel"
      :placeholder="loadPlaceholder"
      :button-text="loadButtonText"
      @load="$emit('load')"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import CreateCard from "./CreateCard.vue";
import LoadSection from "./LoadSection.vue";

const props = defineProps<{
  modelValue: string;
  createTitle: string;
  createDesc: string;
  dividerText: string;
  loadLabel: string;
  loadPlaceholder: string;
  loadButtonText: string;
}>();

const emit = defineEmits<{
  "update:modelValue": [value: string];
  create: [];
  load: [];
}>();

const inputValue = computed({
  get: () => props.modelValue,
  set: (val) => emit("update:modelValue", val),
});
</script>

<style lang="scss" scoped>
.main-card {
  position: relative;
  z-index: 10;
  background: var(--multi-card-bg);
  border: 1px solid var(--multi-card-border);
  border-radius: 24px;
  padding: 24px;
  margin-bottom: 24px;
  backdrop-filter: blur(20px);
}

.divider {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 20px;
}

.divider-line {
  flex: 1;
  height: 1px;
  background: var(--multi-divider);
}

.divider-text {
  font-size: 11px;
  font-weight: 600;
  color: var(--multi-text-soft);
  letter-spacing: 0.1em;
}

@media (max-width: 767px) {
  .main-card {
    padding: 16px;
    border-radius: 16px;
  }
}

@media (min-width: 1024px) {
  .main-card {
    padding: 32px;
  }
}
</style>
