// apps/explorer/src/pages/index/components/SearchPanel.vue
<template>
  <NeoCard variant="erobo-neo" class="mb-6">
    <div class="search-box-neo mb-4">
      <NeoInput
        :modelValue="searchQuery"
        @update:modelValue="$emit('update:searchQuery', $event)"
        :placeholder="t('searchPlaceholder')"
        @confirm="$emit('search')"
        class="mb-2 flex-1"
      />
      <NeoButton variant="primary" block @click="$emit('search')" :loading="isLoading">
        {{ t("search") }}
      </NeoButton>
    </div>

    <div class="network-toggle flex gap-2">
      <NeoButton
        :variant="selectedNetwork === 'mainnet' ? 'success' : 'secondary'"
        size="sm"
        class="flex-1"
        @click="$emit('update:selectedNetwork', 'mainnet')"
      >
        {{ t("mainnet") }}
      </NeoButton>
      <NeoButton
        :variant="selectedNetwork === 'testnet' ? 'warning' : 'secondary'"
        size="sm"
        class="flex-1"
        @click="$emit('update:selectedNetwork', 'testnet')"
      >
        {{ t("testnet") }}
      </NeoButton>
    </div>
  </NeoCard>
</template>

<script setup lang="ts">
import { NeoCard, NeoInput, NeoButton } from "@shared/components";

defineProps<{
  searchQuery: string;
  selectedNetwork: "mainnet" | "testnet";
  isLoading: boolean;
  t: (key: string, ...args: unknown[]) => string;
}>();

defineEmits<{
  (e: "update:searchQuery", value: string): void;
  (e: "update:selectedNetwork", value: "mainnet" | "testnet"): void;
  (e: "search"): void;
}>();
</script>

<style lang="scss" scoped>
@use "@shared/styles/tokens.scss" as *;
@use "@shared/styles/variables.scss" as *;

.search-box-neo {
  display: flex;
  flex-direction: column;
}
.mb-2 {
  margin-bottom: 8px;
}
.mb-4 {
  margin-bottom: 16px;
}
.mb-6 {
  margin-bottom: 24px;
}
.network-toggle {
  margin-top: 24px;
  border-top: 1px solid rgba(255, 255, 255, 0.05);
  padding-top: 24px;
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}
.flex-1 {
  flex: 1;
}
</style>

// apps/explorer/src/components/SearchPanel.tsx
import { NeoButton, NeoCard, NeoInput } from "@shared/components-react";
import "./SearchPanel.scss";

interface SearchPanelProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  searchQuery: string;
  selectedNetwork: "mainnet" | "testnet";
  isSearching: boolean;
  onUpdateSearchQuery: (value: string) => void;
  onUpdateSelectedNetwork: (value: "mainnet" | "testnet") => void;
  onSearch: () => void;
}

export default function SearchPanel({
  t,
  searchQuery,
  selectedNetwork,
  isSearching,
  onUpdateSearchQuery,
  onUpdateSelectedNetwork,
  onSearch,
}: SearchPanelProps) {
  return (
    <NeoCard variant="erobo" className="search-card">
      <div className="search-box">
        <NeoInput
          value={searchQuery}
          placeholder={t("searchPlaceholder")}
          onChange={onUpdateSearchQuery}
          className="search-input"
        />
        <NeoButton
          variant="primary"
          block
          loading={isSearching}
          onClick={onSearch}
        >
          {t("search")}
        </NeoButton>
      </div>

      <div className="network-toggle">
        <NeoButton
          variant={selectedNetwork === "mainnet" ? "success" : "secondary"}
          size="sm"
          className="toggle-btn"
          onClick={() => onUpdateSelectedNetwork("mainnet")}
        >
          {t("mainnet")}
        </NeoButton>
        <NeoButton
          variant={selectedNetwork === "testnet" ? "warning" : "secondary"}
          size="sm"
          className="toggle-btn"
          onClick={() => onUpdateSelectedNetwork("testnet")}
        >
          {t("testnet")}
        </NeoButton>
      </div>
    </NeoCard>
  );
}
