// apps/explorer/src/components/SearchPanel.vue
<template>
  <NeoCard variant="erobo-neo" class="search-card">
    <div class="search-box">
      <NeoInput
        :modelValue="searchQuery"
        @update:modelValue="$emit('update:searchQuery', $event)"
        :placeholder="t('searchPlaceholder')"
        @confirm="$emit('search')"
        class="search-input"
      />
      <NeoButton
        type="button"
        variant="primary"
        block
        :loading="isSearching"
        @click="$emit('search')"
      >
        {{ t("search") }}
      </NeoButton>
    </div>

    <div class="network-toggle">
      <NeoButton
        :variant="selectedNetwork === 'mainnet' ? 'success' : 'secondary'"
        size="sm"
        class="toggle-btn"
        @click="$emit('update:selectedNetwork', 'mainnet')"
      >
        {{ t("mainnet") }}
      </NeoButton>
      <NeoButton
        :variant="selectedNetwork === 'testnet' ? 'warning' : 'secondary'"
        size="sm"
        class="toggle-btn"
        @click="$emit('update:selectedNetwork', 'testnet')"
      >
        {{ t("testnet") }}
      </NeoButton>
    </div>
  </NeoCard>
</template>

<script setup lang="ts">
import { NeoCard, NeoInput, NeoButton } from "@shared/components";

defineProps<{
  t: (key: string, params?: Record<string, string | number>) => string;
  searchQuery: string;
  selectedNetwork: "mainnet" | "testnet";
  isSearching: boolean;
}>();

defineEmits<{
  "update:searchQuery": [value: string];
  "update:selectedNetwork": [value: "mainnet" | "testnet"];
  search: [];
}>();
</script>

<style lang="scss" scoped>
.search-card {
  width: 100%;
}

.search-box {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 16px;
}

.network-toggle {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
  margin-top: 16px;
  border-top: 1px solid rgba(255, 255, 255, 0.05);
  padding-top: 16px;
}
</style>

// apps/explorer/src/components/SearchPanel.tsx
import { NeoButton, NeoCard, NeoInput } from "@shared/components-react";
import "./SearchPanel.scss";

interface SearchPanelProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  searchQuery: string;
  selectedNetwork: "mainnet" | "testnet";
  isSearching: boolean;
  onUpdateSearchQuery: (value: string) => void;
  onUpdateSelectedNetwork: (value: "mainnet" | "testnet") => void;
  onSearch: () => void;
}

export default function SearchPanel({
  t,
  searchQuery,
  selectedNetwork,
  isSearching,
  onUpdateSearchQuery,
  onUpdateSelectedNetwork,
  onSearch,
}: SearchPanelProps) {
  return (
    <NeoCard variant="erobo" className="search-card">
      <div className="search-box">
        <NeoInput
          value={searchQuery}
          placeholder={t("searchPlaceholder")}
          onChange={onUpdateSearchQuery}
          className="search-input"
        />
        <NeoButton
          variant="primary"
          block
          loading={isSearching}
          onClick={onSearch}
        >
          {t("search")}
        </NeoButton>
      </div>

      <div className="network-toggle">
        <NeoButton
          variant={selectedNetwork === "mainnet" ? "success" : "secondary"}
          size="sm"
          className="toggle-btn"
          onClick={() => onUpdateSelectedNetwork("mainnet")}
        >
          {t("mainnet")}
        </NeoButton>
        <NeoButton
          variant={selectedNetwork === "testnet" ? "warning" : "secondary"}
          size="sm"
          className="toggle-btn"
          onClick={() => onUpdateSelectedNetwork("testnet")}
        >
          {t("testnet")}
        </NeoButton>
      </div>
    </NeoCard>
  );
}
