// apps/event-ticket-pass/src/pages/index/components/EventList.vue
<template>
  <NeoCard variant="erobo" class="event-list">
    <div class="events-header">
      <span class="section-title">{{ t("yourEvents") }}</span>
      <NeoButton size="sm" variant="secondary" :loading="isRefreshing" @click="$emit('refresh')">
        {{ t("refresh") }}
      </NeoButton>
    </div>

    <div v-if="!address" class="empty-state">
      <NeoCard variant="erobo" class="p-6 text-center">
        <span class="mb-3 block text-sm">{{ t("walletNotConnected") }}</span>
        <NeoButton size="sm" variant="primary" @click="$emit('connect')">
          {{ t("connectWallet") }}
        </NeoButton>
      </NeoCard>
    </div>

    <template v-else>
      <ItemList :items="events" item-key="id" :empty-text="t('emptyEvents')">
        <template #empty>
          <NeoCard variant="erobo" class="p-6 text-center opacity-70">
            <span class="text-xs">{{ t("emptyEvents") }}</span>
          </NeoCard>
        </template>
        <template #item="{ item: event }">
          <EventDetails
            :event="event"
            :toggling-id="togglingId"
            @issue="$emit('issue', $event)"
            @toggle="$emit('toggle', $event)"
          />
        </template>
      </ItemList>
    </template>
  </NeoCard>
</template>

<script setup lang="ts">
import { NeoCard, NeoButton, ItemList } from "@shared/components";
import { createUseI18n } from "@shared/composables";
import { messages } from "@/locale/messages";
import type { EventItem } from "@/types";

defineProps<{
  address: string | null;
  events: EventItem[];
  isRefreshing: boolean;
  togglingId: string | null;
}>();

const { t } = createUseI18n(messages)();

defineEmits<{
  (e: "refresh"): void;
  (e: "connect"): void;
  (e: "issue", event: EventItem): void;
  (e: "toggle", event: EventItem): void;
}>();
</script>

<style lang="scss" scoped>
.events-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.section-title {
  font-size: 18px;
  font-weight: 700;
}

.event-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.event-cards {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.empty-state {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
</style>

// apps/event-ticket-pass/src/pages/index/components/EventList.tsx
import { NeoCard, NeoButton } from "@shared/components-react";

interface EventListProps {
  address: string | null; events: unknown[]; isRefreshing: boolean; togglingId: string | null;
  onRefresh: () => void; onConnect: () => void; onIssue: (event: unknown) => void; onToggle: (event: unknown) => void;
  t: (key: string) => string;
}

export default function EventList({ address, events, isRefreshing, togglingId, onRefresh, onConnect, onIssue, onToggle, t }: EventListProps) {
  return (
    <NeoCard title={t("yourEvents")}>
      <div className="events-header">
        <NeoButton size="sm" variant="secondary" loading={isRefreshing} onClick={onRefresh}>{t("refresh")}</NeoButton>
      </div>
      {!address ? (
        <div className="empty-state">
          <span>{t("walletNotConnected")}</span>
          <NeoButton size="sm" variant="primary" onClick={onConnect}>{t("connectWallet")}</NeoButton>
        </div>
      ) : events.length === 0 ? (
        <span>{t("emptyEvents")}</span>
      ) : (
        (events as Array<Record<string, unknown>>).map((event) => (
          <div key={String(event.id)} className="event-card">
            <span>{String(event.name || event.id)}</span>
          </div>
        ))
      )}
    </NeoCard>
  );
}
