// apps/daily-checkin/src/components/StreakDisplay.vue
<template>
  <div class="streak-section">
    <div :class="['streak-fire-ring', streakTier, { active: currentStreak > 0 }]">
      <!-- Flame icon that grows with streak -->
      <div class="flame-stack" aria-hidden="true">
        <span class="flame flame-core">{{ flameEmoji }}</span>
        <span v-if="currentStreak >= 7" class="flame flame-outer">{{ flameEmoji }}</span>
        <span v-if="currentStreak >= 30" class="flame flame-inferno">{{ flameEmoji }}</span>
      </div>
      <span class="streak-number">{{ currentStreak }}</span>
    </div>
    <span class="streak-text">{{ t("dayStreak") }}</span>
    <span class="streak-tier-badge" :class="streakTier">{{ streakTierLabel }}</span>
    <span class="streak-best-text">
      {{ t("bestStreak") }}: {{ highestStreak }} {{ t("days") }}
    </span>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";

const props = defineProps<{
  t: (key: string, params?: Record<string, string | number>) => string;
  currentStreak: number;
  highestStreak: number;
}>();

const flameEmoji = "\uD83D\uDD25";

const streakTier = computed(() => {
  if (props.currentStreak >= 30) return "inferno";
  if (props.currentStreak >= 7) return "blaze";
  if (props.currentStreak > 0) return "spark";
  return "cold";
});

const streakTierLabel = computed(() => {
  if (props.currentStreak >= 30) return "INFERNO";
  if (props.currentStreak >= 7) return "BLAZE";
  if (props.currentStreak > 0) return "SPARK";
  return "";
});
</script>

<style lang="scss" scoped>
@use "@shared/styles/variables.scss" as *;

.streak-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
}

.streak-fire-ring {
  width: 90px;
  height: 90px;
  border-radius: 50%;
  background: rgba(0, 0, 0, 0.3);
  border: 3px solid rgba(255, 255, 255, 0.08);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  transition: all 0.5s ease;
  position: relative;

  &.active {
    border-color: rgba(251, 146, 60, 0.4);
    box-shadow:
      0 0 20px rgba(251, 146, 60, 0.2),
      0 0 40px rgba(251, 146, 60, 0.1);
    animation: fire-pulse 2s ease-in-out infinite alternate;
  }

  &.blaze {
    width: 100px;
    height: 100px;
    border-color: rgba(255, 107, 53, 0.5);
    box-shadow:
      0 0 30px rgba(255, 107, 53, 0.3),
      0 0 60px rgba(255, 107, 53, 0.15);
  }

  &.inferno {
    width: 110px;
    height: 110px;
    border-color: rgba(239, 68, 68, 0.6);
    box-shadow:
      0 0 40px rgba(239, 68, 68, 0.35),
      0 0 80px rgba(255, 107, 53, 0.2),
      0 0 120px rgba(255, 165, 0, 0.1);
    animation: inferno-pulse 1.5s ease-in-out infinite alternate;
  }
}

.flame-stack {
  position: absolute;
  top: -18px;
  display: flex;
  align-items: flex-end;
  justify-content: center;
  gap: 0;
  pointer-events: none;
}

.flame {
  line-height: 1;

  &.flame-core {
    font-size: 20px;
    animation: flame-dance 1s ease-in-out infinite alternate;
  }
  &.flame-outer {
    font-size: 16px;
    position: absolute;
    left: -10px;
    top: 2px;
    animation: flame-dance 1.2s ease-in-out infinite alternate-reverse;
    opacity: 0.8;
  }
  &.flame-inferno {
    font-size: 14px;
    position: absolute;
    right: -10px;
    top: 4px;
    animation: flame-dance 0.8s ease-in-out infinite alternate;
    opacity: 0.7;
  }
}

.streak-number {
  font-size: 28px;
  font-weight: 900;
  font-family: $font-mono;
  background: linear-gradient(180deg, var(--sunrise-streak-start, #fbbf24), var(--sunrise-streak-end, #f97316));
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
  filter: drop-shadow(0 0 8px rgba(251, 191, 36, 0.4));
  position: relative;
  z-index: 2;

  .blaze & {
    font-size: 32px;
    filter: drop-shadow(0 0 12px rgba(255, 107, 53, 0.6));
  }

  .inferno & {
    font-size: 36px;
    background: linear-gradient(180deg, #fff 0%, #fbbf24 50%, #ef4444 100%);
    -webkit-background-clip: text;
    background-clip: text;
    filter: drop-shadow(0 0 16px rgba(239, 68, 68, 0.7));
  }
}

.streak-text {
  font-size: 14px;
  font-weight: 800;
  color: var(--text-primary);
  text-transform: uppercase;
  letter-spacing: 0.1em;
}

.streak-tier-badge {
  font-size: 9px;
  font-weight: 900;
  letter-spacing: 0.2em;
  padding: 2px 10px;
  border-radius: 10px;
  text-transform: uppercase;

  &.spark {
    background: rgba(251, 191, 36, 0.12);
    color: #fbbf24;
    border: 1px solid rgba(251, 191, 36, 0.25);
  }
  &.blaze {
    background: rgba(255, 107, 53, 0.15);
    color: #ff6b35;
    border: 1px solid rgba(255, 107, 53, 0.3);
    box-shadow: 0 0 10px rgba(255, 107, 53, 0.2);
  }
  &.inferno {
    background: rgba(239, 68, 68, 0.2);
    color: #f87171;
    border: 1px solid rgba(239, 68, 68, 0.4);
    box-shadow: 0 0 15px rgba(239, 68, 68, 0.3);
    animation: badge-flicker 2s ease-in-out infinite;
  }
  &.cold {
    display: none;
  }
}

.streak-best-text {
  font-size: 11px;
  color: rgba(255, 255, 255, 0.4);
  font-weight: 500;
}

@keyframes fire-pulse {
  0% {
    box-shadow:
      0 0 15px rgba(251, 146, 60, 0.15),
      0 0 30px rgba(251, 146, 60, 0.08);
  }
  100% {
    box-shadow:
      0 0 25px rgba(251, 146, 60, 0.25),
      0 0 50px rgba(251, 146, 60, 0.12);
  }
}

@keyframes inferno-pulse {
  0% {
    box-shadow:
      0 0 30px rgba(239, 68, 68, 0.25),
      0 0 60px rgba(255, 107, 53, 0.15);
  }
  100% {
    box-shadow:
      0 0 50px rgba(239, 68, 68, 0.4),
      0 0 100px rgba(255, 107, 53, 0.25),
      0 0 140px rgba(255, 165, 0, 0.1);
  }
}

@keyframes flame-dance {
  0% { transform: translateY(0) scale(1) rotate(-5deg); }
  100% { transform: translateY(-4px) scale(1.15) rotate(5deg); }
}

@keyframes badge-flicker {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.7; }
}

@media (max-width: 480px) {
  .streak-fire-ring {
    width: 72px;
    height: 72px;
    &.blaze { width: 80px; height: 80px; }
    &.inferno { width: 88px; height: 88px; }
  }
  .streak-number {
    font-size: 22px;
    .blaze & { font-size: 26px; }
    .inferno & { font-size: 28px; }
  }
}

@media (prefers-reduced-motion: reduce) {
  .streak-fire-ring, .flame, .streak-tier-badge {
    animation: none;
    transition: none;
  }
}
</style>

// apps/daily-checkin/src/components/StreakDisplay.tsx
import { useMemo } from "react";
import "./StreakDisplay.scss";

interface StreakDisplayProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  currentStreak: number;
  highestStreak: number;
}

export default function StreakDisplay({ t, currentStreak, highestStreak }: StreakDisplayProps) {
  const flameEmoji = "\uD83D\uDD25";

  const streakTier = useMemo(() => {
    if (currentStreak >= 30) return "inferno";
    if (currentStreak >= 7) return "blaze";
    if (currentStreak > 0) return "spark";
    return "cold";
  }, [currentStreak]);

  const streakTierLabel = useMemo(() => {
    if (currentStreak >= 30) return "INFERNO";
    if (currentStreak >= 7) return "BLAZE";
    if (currentStreak > 0) return "SPARK";
    return "";
  }, [currentStreak]);

  return (
    <div className="streak-section">
      <div className={`streak-fire-ring ${streakTier}${currentStreak > 0 ? " active" : ""}`}>
        <div className="flame-stack" aria-hidden="true">
          <span className="flame flame-core">{flameEmoji}</span>
          {currentStreak >= 7 && <span className="flame flame-outer">{flameEmoji}</span>}
          {currentStreak >= 30 && <span className="flame flame-inferno">{flameEmoji}</span>}
        </div>
        <span className="streak-number">{currentStreak}</span>
      </div>
      <span className="streak-text">{t("dayStreak")}</span>
      <span className={`streak-tier-badge ${streakTier}`}>{streakTierLabel}</span>
      <span className="streak-best-text">
        {t("bestStreak")}: {highestStreak} {t("days")}
      </span>
    </div>
  );
}
