// apps/shared/components/DetailCardGrid.tsx
import { useI18n } from "@shared/react";
import "./DetailCardGrid.scss";

export interface DetailCardGridItem {
  label: string;
  value: string | number;
}

export interface DetailCardGridProps {
  items: DetailCardGridItem[];
  columns?: 2 | 3;
  className?: string;
}

export function DetailCardGrid({ items, columns = 2, className }: DetailCardGridProps) {
  const { t } = useI18n();

  const classes = [
    "detail-grid",
    `detail-grid--cols-${columns}`,
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div className={classes} role="list" aria-label={t("detailsLabel")}>
      {items.map((item) => (
        <div key={item.label} className="detail-card" role="listitem" aria-label={`${item.label}: ${item.value}`}>
          <span className="detail-label">{item.label}</span>
          <span className="detail-value">{item.value}</span>
        </div>
      ))}
    </div>
  );
}

export default DetailCardGrid;

// apps/shared/components/DetailCardGrid.vue
<template>
  <div class="detail-grid" :class="columnsClass" role="list" :aria-label="t('detailsLabel')">
    <div v-for="item in items" :key="item.label" class="detail-card" role="listitem" :aria-label="`${item.label}: ${item.value}`">
      <span class="detail-label">{{ item.label }}</span>
      <span class="detail-value">{{ item.value }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { createUseI18n } from "@shared/composables";
import { messages } from "@shared/locale/messages";

const { t } = createUseI18n(messages)();

const props = withDefaults(defineProps<{
  items: Array<{ label: string; value: string | number }>;
  columns?: 2 | 3;
}>(), {
  columns: 2,
});

const columnsClass = computed(() => `detail-grid--cols-${props.columns}`);
</script>

<style scoped lang="scss">
@use "@shared/styles/console-common" as console;

.detail-grid {
  @include console.detail-grid;

  &--cols-3 {
    @include console.detail-grid(3, 900px);
  }
}

.detail-card {
  @include console.detail-card;
}

.detail-label {
  @include console.label;
  letter-spacing: 0.12em;
}

.detail-value {
  @include console.value;
  margin-top: 8px;
}
</style>
