// apps/shared/components/ItemList.vue
<template>
  <div class="item-list" role="list" :aria-label="ariaLabel || t('listLabel')">
    <!-- Loading state -->
    <div v-if="loading" class="item-list__loading" role="status" :aria-label="t('loading')">
      <div class="item-list__spinner" aria-hidden="true" />
      <span v-if="loadingText" class="item-list__loading-text">{{ loadingText }}</span>
    </div>

    <!-- Empty state -->
    <div v-else-if="!items || items.length === 0" class="item-list__empty" role="status">
      <slot name="empty">
        <span class="item-list__empty-text">{{ emptyText ?? t("emptyStateHint") }}</span>
        <button
          v-if="emptyActionLabel"
          type="button"
          class="item-list__empty-action"
          @click="$emit('empty-action')"
        >
          {{ emptyActionLabel ?? t("getStarted") }}
        </button>
      </slot>
    </div>

    <!-- Items -->
    <template v-else>
      <div
        class="item-list__content"
        :class="{ 'item-list__content--scrollable': scrollable }"
        :style="maxHeight ? { maxHeight: `${maxHeight}px` } : undefined"
      >
        <div
          v-for="(item, index) in displayedItems"
          :key="itemKey ? item[itemKey] : (item.id ?? index)"
          class="item-list__item"
          role="listitem"
        >
          <slot name="item" :item="item" :index="index" />
        </div>
      </div>

      <!-- Load more -->
      <button
        v-if="hasMore"
        type="button"
        class="item-list__load-more"
        :disabled="loading"
        :aria-disabled="loading"
        @click="$emit('load-more')"
      >
        <span>{{ loadMoreText ?? t("loadMore") }}</span>
      </button>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "@shared/composables/useI18n";

const props = withDefaults(
  defineProps<{
    items: Array<Record<string, unknown>>;
    loading?: boolean;
    loadingText?: string;
    emptyText?: string;
    /** Key field on item objects for :key binding */
    itemKey?: string;
    scrollable?: boolean;
    /** Max height in px (enables overflow scroll automatically) */
    maxHeight?: number;
    /** Number of items to display (for client-side pagination). 0 = show all. */
    limit?: number;
    /** Whether more items can be loaded (shows load-more button) */
    hasMore?: boolean;
    /** Label for the load-more button */
    loadMoreText?: string;
    /** Accessibility label for screen readers */
    ariaLabel?: string;
    /** Label for the empty-state action button (shows button when provided) */
    emptyActionLabel?: string;
  }>(),
  {
    loading: false,
    loadingText: undefined,
    emptyText: undefined,
    itemKey: undefined,
    scrollable: false,
    maxHeight: undefined,
    limit: 0,
    hasMore: false,
    loadMoreText: undefined,
    ariaLabel: undefined,
    emptyActionLabel: undefined,
  }
);

defineEmits<{
  (e: "load-more"): void;
  (e: "empty-action"): void;
}>();

const { t } = useI18n();

const displayedItems = computed(() => {
  if (props.limit > 0) {
    return props.items.slice(0, props.limit);
  }
  return props.items;
});
</script>

<style lang="scss" scoped>
@use "../styles/tokens.scss" as *;

.item-list {
  &__loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: $spacing-8;
    gap: $spacing-3;
  }

  &__spinner {
    width: 24px;
    height: 24px;
    border: 2px solid var(--border-color, rgba(255, 255, 255, 0.1));
    border-top-color: var(--text-primary, #ffffff);
    border-radius: 50%;
    animation: itemListSpin 0.8s linear infinite;
  }

  &__loading-text {
    font-size: $font-size-sm;
    font-weight: $font-weight-medium;
    color: var(--text-secondary, rgba(255, 255, 255, 0.5));
  }

  &__empty {
    text-align: center;
    padding: $spacing-6;
  }

  &__empty-text {
    display: block;
    font-size: $font-size-md;
    font-weight: $font-weight-medium;
    color: var(--text-secondary, rgba(255, 255, 255, 0.5));
  }

  &__empty-action {
    display: inline-block;
    margin-top: $spacing-3;
    padding: $spacing-2 $spacing-4;
    font-size: $font-size-sm;
    font-weight: $font-weight-bold;
    color: var(--text-primary, #ffffff);
    background: var(--accent-primary, #3b82f6);
    border: none;
    border-radius: 8px;
    cursor: pointer;
    transition: background 0.2s ease;

    &:hover {
      background: var(--accent-hover, #2563eb);
    }

    &:focus-visible {
      outline: 2px solid var(--accent-primary, #3b82f6);
      outline-offset: 2px;
      box-shadow: 0 0 0 4px rgba(59, 130, 246, 0.15);
    }
  }

  &__content {
    display: flex;
    flex-direction: column;
    gap: $spacing-2;

    &--scrollable {
      overflow-y: auto;
      -webkit-overflow-scrolling: touch;
    }
  }

  &__item {
    background: var(--bg-card, rgba(255, 255, 255, 0.03));
    border: 1px solid var(--border-color, rgba(255, 255, 255, 0.05));
    border-radius: 12px;
    padding: $spacing-3;
    transition: background 0.2s ease;

    &:hover {
      background: var(--bg-elevated, rgba(255, 255, 255, 0.05));
    }
  }

  &__load-more {
    text-align: center;
    padding: $spacing-3;
    margin-top: $spacing-2;
    font-size: $font-size-sm;
    font-weight: $font-weight-bold;
    color: var(--text-secondary, rgba(255, 255, 255, 0.5));
    text-transform: uppercase;
    letter-spacing: 0.05em;
    cursor: pointer;
    border-radius: 8px;
    border: none;
    appearance: none;
    background: transparent;
    transition:
      background 0.2s ease,
      color 0.2s ease;

    &:hover {
      background: rgba(255, 255, 255, 0.05);
      color: var(--text-primary, #ffffff);
    }

    &:focus-visible {
      outline: 2px solid var(--accent-primary, #3b82f6);
      outline-offset: 2px;
      box-shadow: 0 0 0 4px rgba(59, 130, 246, 0.15);
    }
  }
}

@keyframes itemListSpin {
  to {
    transform: rotate(360deg);
  }
}

@media (prefers-reduced-motion: reduce) {
  .item-list {
    &__spinner {
      animation: none;
    }

    &__item {
      transition: none;
    }
  }
}
</style>

// apps/shared/components/ItemList.tsx
import { useMemo, type ReactNode } from "react";
import { useI18n } from "@shared/react";
import "./ItemList.scss";

export interface ItemListProps {
  items: Array<Record<string, unknown>>;
  loading?: boolean;
  loadingText?: string;
  emptyText?: string;
  /** Key field on item objects for :key binding */
  itemKey?: string;
  scrollable?: boolean;
  /** Max height in px (enables overflow scroll automatically) */
  maxHeight?: number;
  /** Number of items to display (for client-side pagination). 0 = show all. */
  limit?: number;
  /** Whether more items can be loaded (shows load-more button) */
  hasMore?: boolean;
  /** Label for the load-more button */
  loadMoreText?: string;
  /** Accessibility label for screen readers */
  ariaLabel?: string;
  /** Label for the empty-state action button (shows button when provided) */
  emptyActionLabel?: string;
  className?: string;
  /** Render function for each item */
  renderItem?: (item: Record<string, unknown>, index: number) => ReactNode;
  /** Custom empty state content */
  renderEmpty?: () => ReactNode;
  onLoadMore?: () => void;
  onEmptyAction?: () => void;
}

export function ItemList({
  items,
  loading = false,
  loadingText,
  emptyText,
  itemKey,
  scrollable = false,
  maxHeight,
  limit = 0,
  hasMore = false,
  loadMoreText,
  ariaLabel,
  emptyActionLabel,
  className,
  renderItem,
  renderEmpty,
  onLoadMore,
  onEmptyAction,
}: ItemListProps) {
  const { t } = useI18n();

  const displayedItems = useMemo(() => {
    if (limit > 0) return items.slice(0, limit);
    return items;
  }, [items, limit]);

  const classes = ["item-list", className].filter(Boolean).join(" ");

  if (loading) {
    return (
      <div className={classes} role="list" aria-label={ariaLabel || t("listLabel")}>
        <div className="item-list__loading" role="status" aria-label={t("loading")}>
          <div className="item-list__spinner" aria-hidden="true" />
          {loadingText && <span className="item-list__loading-text">{loadingText}</span>}
        </div>
      </div>
    );
  }

  if (!items || items.length === 0) {
    return (
      <div className={classes} role="list" aria-label={ariaLabel || t("listLabel")}>
        <div className="item-list__empty" role="status">
          {renderEmpty ? (
            renderEmpty()
          ) : (
            <>
              <span className="item-list__empty-text">{emptyText ?? t("emptyStateHint")}</span>
              {emptyActionLabel && (
                <button type="button" className="item-list__empty-action" onClick={onEmptyAction}>
                  {emptyActionLabel ?? t("getStarted")}
                </button>
              )}
            </>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className={classes} role="list" aria-label={ariaLabel || t("listLabel")}>
      <div
        className={[
          "item-list__content",
          scrollable && "item-list__content--scrollable",
        ]
          .filter(Boolean)
          .join(" ")}
        style={maxHeight ? { maxHeight: `${maxHeight}px` } : undefined}
      >
        {displayedItems.map((item, index) => {
          const key = itemKey ? String(item[itemKey]) : String(item.id ?? index);
          return (
            <div key={key} className="item-list__item" role="listitem">
              {renderItem?.(item, index)}
            </div>
          );
        })}
      </div>

      {hasMore && (
        <button
          type="button"
          className="item-list__load-more"
          disabled={loading}
          aria-disabled={loading}
          onClick={onLoadMore}
        >
          <span>{loadMoreText ?? t("loadMore")}</span>
        </button>
      )}
    </div>
  );
}

export default ItemList;
