// apps/shared/components/MiniAppOperationPanel.vue
<template>
  <div class="operation-panels">
    <NeoCard
      v-for="operation in operations"
      :key="operation.key"
      variant="erobo"
      :title="resolveTitle(operation)"
      class="operation-card"
    >
      <!-- Description -->
      <p
        v-if="resolveDescription(operation)"
        class="operation-description"
      >
        {{ resolveDescription(operation) }}
      </p>

      <!-- Form Fields -->
      <div v-if="operation.fields?.length" class="operation-fields">
        <div
          v-for="field in operation.fields"
          :key="field.key"
          class="operation-field"
        >
          <!-- Amount field -->
          <NeoInput
            v-if="field.type === 'amount'"
            :model-value="getFieldValue(operation.key, field.key)"
            type="number"
            :label="resolveFieldLabel(field)"
            :placeholder="field.placeholder ?? '0.00'"
            :min="field.validation?.min?.toString()"
            :max="field.validation?.max?.toString()"
            :required="field.required"
            suffix="GAS"
            :error="getFieldError(operation.key, field.key)"
            @update:model-value="setFieldValue(operation.key, field.key, $event)"
          />

          <!-- Address field -->
          <NeoInput
            v-else-if="field.type === 'address'"
            :model-value="getFieldValue(operation.key, field.key)"
            type="text"
            :label="resolveFieldLabel(field)"
            :placeholder="field.placeholder ?? 'N...'"
            :required="field.required"
            :error="getFieldError(operation.key, field.key)"
            suffix-icon="wallet"
            @update:model-value="setFieldValue(operation.key, field.key, $event)"
          />

          <!-- Number field -->
          <NeoInput
            v-else-if="field.type === 'number'"
            :model-value="getFieldValue(operation.key, field.key)"
            type="number"
            :label="resolveFieldLabel(field)"
            :placeholder="field.placeholder ?? '0'"
            :min="field.validation?.min?.toString()"
            :max="field.validation?.max?.toString()"
            :required="field.required"
            :error="getFieldError(operation.key, field.key)"
            @update:model-value="setFieldValue(operation.key, field.key, $event)"
          />

          <!-- Text field -->
          <NeoInput
            v-else-if="field.type === 'text'"
            :model-value="getFieldValue(operation.key, field.key)"
            type="text"
            :label="resolveFieldLabel(field)"
            :placeholder="field.placeholder ?? ''"
            :required="field.required"
            :error="getFieldError(operation.key, field.key)"
            @update:model-value="setFieldValue(operation.key, field.key, $event)"
          />

          <!-- Select field -->
          <div v-else-if="field.type === 'select'" class="field-select">
            <label v-if="resolveFieldLabel(field)" class="field-label">
              {{ resolveFieldLabel(field) }}
            </label>
            <select
              class="neo-select"
              :value="getFieldValue(operation.key, field.key)"
              :required="field.required"
              :aria-label="resolveFieldLabel(field) || field.key"
              @change="setFieldValue(operation.key, field.key, ($event.target as HTMLSelectElement).value)"
            >
              <option value="" disabled>
                {{ field.placeholder || t("select") }}
              </option>
              <option
                v-for="opt in (field.options ?? [])"
                :key="opt.value"
                :value="opt.value"
              >
                {{ opt.labelKey ? t(opt.labelKey) : (opt.label ?? opt.value) }}
              </option>
            </select>
          </div>

          <!-- Toggle field -->
          <div v-else-if="field.type === 'toggle'" class="field-toggle">
            <label class="toggle-label">
              <input
                type="checkbox"
                class="toggle-input"
                :checked="Boolean(getFieldValue(operation.key, field.key))"
                :aria-label="resolveFieldLabel(field) || field.key"
                @change="setFieldValue(operation.key, field.key, ($event.target as HTMLInputElement).checked)"
              />
              <span class="toggle-switch" />
              <span v-if="resolveFieldLabel(field)" class="toggle-text">
                {{ resolveFieldLabel(field) }}
              </span>
            </label>
          </div>
        </div>
      </div>

      <!-- State-bound summary (reads from reactive state) -->
      <div v-if="hasStateSummary(operation)" class="operation-summary">
        <div
          v-for="stat in getOperationStats(operation)"
          :key="stat.key"
          class="summary-row"
        >
          <span class="summary-label">{{ stat.label }}</span>
          <span class="summary-value">{{ stat.value }}</span>
        </div>
      </div>

      <!-- Action Button -->
      <NeoButton
        v-if="resolveActionLabel(operation)"
        variant="primary"
        size="lg"
        block
        :loading="isSubmitting(operation.key)"
        :disabled="isSubmitting(operation.key) || !isFormValid(operation.key)"
        :aria-label="resolveActionLabel(operation)"
        class="operation-action-btn"
        @click="submitOperation(operation)"
      >
        {{ resolveActionLabel(operation) }}
      </NeoButton>
    </NeoCard>
  </div>
</template>

<script setup lang="ts">
/**
 * MiniAppOperationPanel — Renders operation forms and action buttons
 *
 * Reads operation definitions from the manifest and renders a form panel
 * for each operation. Each operation can have:
 * - Form fields (amount, address, select, toggle, number, text)
 * - A state-bound summary section
 * - An action button that triggers a registered handler
 *
 * The action button calls the parent via @action emit with the operation
 * key and collected form data. The parent (MiniAppRoot) dispatches to
 * the registered action handler.
 */

import { ref, reactive, computed } from "vue";
import type { Ref } from "vue";
import type { OperationDefinition, OperationFieldDefinition } from "@shared/types/miniapp-manifest";
import NeoCard from "./NeoCard.vue";
import NeoButton from "./NeoButton.vue";
import NeoInput from "./NeoInput.vue";

// ============================================================================
// Props & Emits
// ============================================================================

const props = defineProps<{
  /** Operation definitions from manifest */
  operations: OperationDefinition[];
  /** Translation function */
  t: (key: string, params?: Record<string, string | number>) => string;
  /** Reactive state for reading stat values */
  state: Record<string, Ref<unknown>>;
  /** Async callback for action handling — awaited to track submission state */
  onAction?: (operationKey: string, formData: Record<string, unknown>) => Promise<void>;
  /**
   * When true, amount fields with format "gas" are auto-scaled to Fixed8
   * (value * 1e8) in the emitted formData. Defaults to false to preserve
   * backward compatibility.
   */
  scaleAmounts?: boolean;
}>();

// ============================================================================
// Form State
// ============================================================================

/**
 * Form data store: { operationKey: { fieldKey: value } }
 * Initialized from field defaults.
 */
const formData: Record<string, Record<string, unknown>> = reactive({});
const formErrors: Record<string, Record<string, string>> = reactive({});
const submittingOps = ref<Set<string>>(new Set());

/** Initialize form data for all operations on setup */
for (const operation of props.operations) {
  formData[operation.key] = {};
  formErrors[operation.key] = {};
  if (operation.fields) {
    for (const field of operation.fields) {
      if (field.default !== undefined) {
        formData[operation.key][field.key] = field.default;
      } else {
        formData[operation.key][field.key] = field.type === "toggle" ? false : "";
      }
    }
  }
}

// ============================================================================
// Field Accessors
// ============================================================================

function getFieldValue(opKey: string, fieldKey: string): unknown {
  return formData[opKey]?.[fieldKey] ?? "";
}

function setFieldValue(opKey: string, fieldKey: string, value: unknown) {
  if (!formData[opKey]) {
    formData[opKey] = {};
  }
  formData[opKey][fieldKey] = value;

  // Clear error on edit
  if (formErrors[opKey]?.[fieldKey]) {
    formErrors[opKey][fieldKey] = "";
  }
}

function getFieldError(opKey: string, fieldKey: string): string | undefined {
  const err = formErrors[opKey]?.[fieldKey];
  return err || undefined;
}

// ============================================================================
// Label Resolution
// ============================================================================

function resolveTitle(op: OperationDefinition): string {
  if (op.titleKey) return props.t(op.titleKey);
  return props.t(op.key);
}

function resolveDescription(op: OperationDefinition): string | undefined {
  if (!op.descriptionKey) return undefined;
  const desc = props.t(op.descriptionKey);
  return desc !== op.descriptionKey ? desc : undefined;
}

function resolveFieldLabel(field: OperationFieldDefinition): string | undefined {
  if (!field.labelKey) return undefined;
  const label = props.t(field.labelKey);
  return label !== field.labelKey ? label : field.labelKey;
}

function resolveActionLabel(op: OperationDefinition): string | undefined {
  if (op.actionKey) {
    const label = props.t(op.actionKey);
    return label !== op.actionKey ? label : op.actionKey;
  }
  if (op.actionMethod) {
    return props.t(op.actionMethod);
  }
  return undefined;
}

// ============================================================================
// State Summary
// ============================================================================

function hasStateSummary(op: OperationDefinition): boolean {
  // Check if the manifest has stats that reference this operation's fields
  return false; // Placeholder — extendable by manifest
}

interface SummaryItem {
  key: string;
  label: string;
  value: string;
}

function getOperationStats(_op: OperationDefinition): SummaryItem[] {
  return []; // Placeholder — extendable by manifest
}

// ============================================================================
// Validation
// ============================================================================

function validateField(opKey: string, field: OperationFieldDefinition): boolean {
  const value = getFieldValue(opKey, field.key);

  // Required check
  if (field.required) {
    if (value === "" || value === null || value === undefined) {
      formErrors[opKey][field.key] = props.t("fieldRequired");
      return false;
    }
  }

  // Numeric range validation
  if (field.type === "amount" || field.type === "number") {
    const num = Number(value);
    if (value !== "" && !isNaN(num)) {
      if (field.validation?.min !== undefined && num < field.validation.min) {
        formErrors[opKey][field.key] = props.t("fieldMinValue", { min: field.validation.min });
        return false;
      }
      if (field.validation?.max !== undefined && num > field.validation.max) {
        formErrors[opKey][field.key] = props.t("fieldMaxValue", { max: field.validation.max });
        return false;
      }
    }
  }

  // Neo N3 address format validation (starts with 'N', 34 chars, base58)
  if (field.type === "address" && value) {
    if (!/^N[A-HJ-NP-Za-km-z1-9]{33}$/.test(value as string)) {
      formErrors[opKey][field.key] = props.t("invalidAddress");
      return false;
    }
  }

  // Pattern validation (skip for empty optional fields)
  if (field.validation?.pattern && typeof value === "string") {
    if (field.required || value !== "") {
      const regex = new RegExp(field.validation.pattern);
      if (!regex.test(value)) {
        formErrors[opKey][field.key] = props.t("fieldInvalidFormat");
        return false;
      }
    }
  }

  return true;
}

function isFormValid(opKey: string): boolean {
  const op = props.operations.find((o) => o.key === opKey);
  if (!op?.fields?.length) return true;

  return op.fields.every((field) => {
    if (!field.required) return true;
    const value = getFieldValue(opKey, field.key);
    return value !== "" && value !== null && value !== undefined;
  });
}

function validateOperation(op: OperationDefinition): boolean {
  if (!op.fields?.length) return true;

  let valid = true;
  for (const field of op.fields) {
    if (!validateField(op.key, field)) {
      valid = false;
    }
  }
  return valid;
}

// ============================================================================
// Submission
// ============================================================================

function isSubmitting(opKey: string): boolean {
  return submittingOps.value.has(opKey);
}

async function submitOperation(op: OperationDefinition) {
  if (!validateOperation(op)) return;
  if (submittingOps.value.has(op.key)) return;
  if (!props.onAction) return;

  submittingOps.value.add(op.key);
  try {
    const data = { ...(formData[op.key] ?? {}) };

    // When scaleAmounts is enabled, auto-scale amount fields to Fixed8 (1e8)
    // so callers receive integer values ready for on-chain submission.
    if (props.scaleAmounts && op.fields) {
      for (const field of op.fields) {
        if (field.type === "amount" && data[field.key] !== "" && data[field.key] != null) {
          const num = Number(data[field.key]);
          if (!isNaN(num)) {
            data[field.key] = Math.round(num * 1e8);
          }
        }
      }
    }

    await props.onAction(op.key, data);
  } finally {
    submittingOps.value.delete(op.key);
  }
}
</script>

<style lang="scss" scoped>
/* ── Operation Panels ── */
.operation-panels {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.operation-card {
  /* Inherits NeoCard erobo variant styling */
}

.operation-description {
  font-size: 13px;
  color: rgba(255, 255, 255, 0.5);
  line-height: 1.5;
  margin-bottom: 16px;
}

/* ── Form Fields ── */
.operation-fields {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-bottom: 16px;
}

.operation-field {
  width: 100%;
}

/* ── Select Field ── */
.field-select {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.field-label {
  font-size: 12px;
  font-weight: 600;
  color: rgba(255, 255, 255, 0.6);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.neo-select {
  width: 100%;
  padding: 10px 12px;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 8px;
  color: rgba(255, 255, 255, 0.9);
  font-size: 14px;
  font-family: inherit;
  outline: none;
  transition: border-color 0.2s ease;
  appearance: none;
  cursor: pointer;

  &:hover {
    border-color: rgba(255, 255, 255, 0.16);
  }

  &:focus {
    border-color: var(--accent, #00e599);
    box-shadow: 0 0 0 2px rgba(0, 229, 153, 0.12);
  }

  option {
    background: #1a1a1a;
    color: rgba(255, 255, 255, 0.9);
  }
}

/* ── Toggle Field ── */
.field-toggle {
  display: flex;
  align-items: center;
}

.toggle-label {
  display: flex;
  align-items: center;
  gap: 10px;
  cursor: pointer;
  user-select: none;
}

.toggle-input {
  position: absolute;
  opacity: 0;
  width: 0;
  height: 0;
  pointer-events: none;
}

.toggle-switch {
  position: relative;
  width: 40px;
  height: 22px;
  background: rgba(255, 255, 255, 0.08);
  border-radius: 11px;
  transition: background 0.2s ease;
  flex-shrink: 0;

  &::after {
    content: "";
    position: absolute;
    top: 2px;
    left: 2px;
    width: 18px;
    height: 18px;
    background: rgba(255, 255, 255, 0.5);
    border-radius: 50%;
    transition: transform 0.2s ease, background 0.2s ease;
  }

  .toggle-input:checked + & {
    background: var(--accent, #00e599);

    &::after {
      transform: translateX(18px);
      background: #fff;
    }
  }

  .toggle-input:focus-visible + & {
    box-shadow: 0 0 0 2px rgba(0, 229, 153, 0.3);
  }
}

.toggle-text {
  font-size: 13px;
  color: rgba(255, 255, 255, 0.7);
  font-weight: 500;
}

/* ── Summary ── */
.operation-summary {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 12px;
  background: rgba(255, 255, 255, 0.02);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 8px;
  margin-bottom: 16px;
}

.summary-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.summary-label {
  font-size: 12px;
  color: rgba(255, 255, 255, 0.45);
  font-weight: 500;
}

.summary-value {
  font-size: 13px;
  color: rgba(255, 255, 255, 0.8);
  font-weight: 600;
  font-family: "JetBrains Mono", "Fira Code", monospace;
}

/* ── Action Button ── */
.operation-action-btn {
  margin-top: 8px;
}
</style>

// apps/shared/components/MiniAppOperationPanel.tsx
/**
 * MiniAppOperationPanel — React equivalent of MiniAppOperationPanel.vue
 *
 * Renders operation forms and action buttons from manifest operation definitions.
 * Each operation can have form fields (amount, address, select, toggle, number, text),
 * a state-bound summary section, and an action button that triggers a registered handler.
 */

import React, {
  useEffect,
  useMemo,
  useState,
  useCallback,
  useRef,
} from "react";
import type {
  OperationDefinition,
  OperationFieldDefinition,
} from "@shared/types/miniapp-manifest";
import type { Observable } from "../react/context";
import type { MiniAppLaunchContext } from "../utils/launch-params";
import "./MiniAppOperationPanel.scss";

// ============================================================================
// Props
// ============================================================================

export interface MiniAppOperationPanelProps {
  /** Operation definitions from manifest */
  operations: OperationDefinition[];
  /** Translation function */
  t: (key: string, params?: Record<string, string | number>) => string;
  /** Reactive state for reading stat values */
  state: Record<string, Observable>;
  /** Async callback for action handling */
  onAction?: (
    operationKey: string,
    formData: Record<string, unknown>,
  ) => Promise<void>;
  /**
   * When true, amount fields are auto-scaled to Fixed8 (value * 1e8)
   * in the emitted formData. Defaults to false.
   */
  scaleAmounts?: boolean;
  launchContext?: MiniAppLaunchContext | null;
}

// ============================================================================
// Helpers
// ============================================================================

function initFieldValue(
  field: OperationFieldDefinition,
  launchParams: Record<string, string>,
): unknown {
  const launched = readLaunchFieldValue(field.key, launchParams);
  if (launched !== undefined && launched !== "") {
    if (field.type === "toggle") {
      return /^(true|1|yes|on)$/i.test(launched);
    }
    return launched;
  }
  if (field.default !== undefined) return field.default;
  return field.type === "toggle" ? false : "";
}

function readLaunchFieldValue(
  fieldKey: string,
  launchParams: Record<string, string>,
): string | undefined {
  const aliases = fieldAliases(fieldKey);
  for (const alias of aliases) {
    const value = launchParams[alias];
    if (value !== undefined && value !== "") return value;
  }
  return undefined;
}

function fieldAliases(fieldKey: string): string[] {
  const normalized = fieldKey.replace(/[-_.:]/g, "").toLowerCase();
  const aliases = [fieldKey];
  if (normalized === "claimkey") aliases.push("key", "code", "k");
  if (normalized === "poolid") aliases.push("pool", "campaignId", "campaign");
  if (normalized === "onegateappid") {
    aliases.push("oneGateId", "onegateAppId", "onegateId");
  }
  if (normalized === "appid" || normalized === "miniappid") {
    aliases.push("app", "miniAppId", "miniappId");
  }
  return Array.from(new Set(aliases));
}

function initFormData(
  operations: OperationDefinition[],
  launchParams: Record<string, string> = {},
): Record<string, Record<string, unknown>> {
  const data: Record<string, Record<string, unknown>> = {};
  for (const operation of operations) {
    const operationData: Record<string, unknown> = {};
    data[operation.key] = operationData;
    if (operation.fields) {
      for (const field of operation.fields) {
        operationData[field.key] = initFieldValue(field, launchParams);
      }
    }
  }
  return data;
}

// ============================================================================
// Component
// ============================================================================

export function MiniAppOperationPanel({
  operations,
  t,
  state: _state,
  onAction,
  scaleAmounts = false,
  launchContext = null,
}: MiniAppOperationPanelProps) {
  const initialFormData = useMemo(
    () => initFormData(operations, launchContext?.params),
    [launchContext?.signature, operations],
  );
  const [formData, setFormData] =
    useState<Record<string, Record<string, unknown>>>(initialFormData);
  const [formErrors, setFormErrors] = useState<
    Record<string, Record<string, string>>
  >(() => {
    const errors: Record<string, Record<string, string>> = {};
    for (const op of operations) {
      errors[op.key] = {};
    }
    return errors;
  });
  const [submittingOps, setSubmittingOps] = useState<Set<string>>(
    () => new Set(),
  );
  const formDataRef = useRef(formData);
  formDataRef.current = formData;
  const operationGroups = useMemo(
    () => splitOperations(operations),
    [operations],
  );
  const [activeOperationKey, setActiveOperationKey] = useState(
    operationGroups.primary[0]?.key ?? operations[0]?.key ?? "",
  );
  const activeOperation =
    operations.find((operation) => operation.key === activeOperationKey) ??
    operationGroups.primary[0] ??
    operations[0];

  useEffect(() => {
    setFormData(initialFormData);
  }, [initialFormData]);

  useEffect(() => {
    const stillExists = operations.some(
      (operation) => operation.key === activeOperationKey,
    );
    if (!stillExists) {
      setActiveOperationKey(
        operationGroups.primary[0]?.key ?? operations[0]?.key ?? "",
      );
    }
  }, [activeOperationKey, operationGroups.primary, operations]);

  // --------------------------------------------------------------------------
  // Field Accessors
  // --------------------------------------------------------------------------

  const getFieldValue = useCallback(
    (opKey: string, fieldKey: string): unknown => {
      return formDataRef.current[opKey]?.[fieldKey] ?? "";
    },
    [],
  );

  const setFieldValue = useCallback(
    (opKey: string, fieldKey: string, value: unknown) => {
      setFormData((prev) => ({
        ...prev,
        [opKey]: { ...(prev[opKey] ?? {}), [fieldKey]: value },
      }));
      // Clear error on edit
      setFormErrors((prev) => {
        if (prev[opKey]?.[fieldKey]) {
          const newErrors = { ...prev };
          newErrors[opKey] = { ...newErrors[opKey] };
          newErrors[opKey][fieldKey] = "";
          return newErrors;
        }
        return prev;
      });
    },
    [],
  );

  const getFieldError = useCallback(
    (opKey: string, fieldKey: string): string | undefined => {
      const err = formErrors[opKey]?.[fieldKey];
      return err || undefined;
    },
    [formErrors],
  );

  // --------------------------------------------------------------------------
  // Label Resolution
  // --------------------------------------------------------------------------

  const resolveTitle = useCallback(
    (op: OperationDefinition): string => {
      if (op.titleKey) return t(op.titleKey);
      return t(op.key);
    },
    [t],
  );

  const resolveDescription = useCallback(
    (op: OperationDefinition): string | undefined => {
      if (!op.descriptionKey) return undefined;
      const desc = t(op.descriptionKey);
      return desc !== op.descriptionKey ? desc : undefined;
    },
    [t],
  );

  const resolveFieldLabel = useCallback(
    (field: OperationFieldDefinition): string | undefined => {
      if (!field.labelKey) return undefined;
      const label = t(field.labelKey);
      return label !== field.labelKey ? label : field.labelKey;
    },
    [t],
  );

  const resolveActionLabel = useCallback(
    (op: OperationDefinition): string | undefined => {
      if (op.actionKey) {
        const label = t(op.actionKey);
        return label !== op.actionKey ? label : op.actionKey;
      }
      if (op.actionMethod) {
        return t(op.actionMethod);
      }
      return undefined;
    },
    [t],
  );

  // --------------------------------------------------------------------------
  // State Summary (placeholder -- extendable by manifest)
  // --------------------------------------------------------------------------

  const hasStateSummary = useCallback((_op: OperationDefinition): boolean => {
    return false;
  }, []);

  const getOperationStats = useCallback(
    (
      _op: OperationDefinition,
    ): Array<{ key: string; label: string; value: string }> => {
      return [];
    },
    [],
  );

  // --------------------------------------------------------------------------
  // Validation
  // --------------------------------------------------------------------------

  const validateField = useCallback(
    (opKey: string, field: OperationFieldDefinition): boolean => {
      const value = formDataRef.current[opKey]?.[field.key] ?? "";
      let errorMsg = "";

      // Required check
      if (field.required) {
        if (value === "" || value === null || value === undefined) {
          errorMsg = t("fieldRequired");
          setFormErrors((prev) => ({
            ...prev,
            [opKey]: { ...(prev[opKey] ?? {}), [field.key]: errorMsg },
          }));
          return false;
        }
      }

      // Numeric range validation
      if (field.type === "amount" || field.type === "number") {
        const num = Number(value);
        if (value !== "" && !isNaN(num)) {
          if (
            field.validation?.min !== undefined &&
            num < field.validation.min
          ) {
            errorMsg = t("fieldMinValue", { min: field.validation.min });
            setFormErrors((prev) => ({
              ...prev,
              [opKey]: { ...(prev[opKey] ?? {}), [field.key]: errorMsg },
            }));
            return false;
          }
          if (
            field.validation?.max !== undefined &&
            num > field.validation.max
          ) {
            errorMsg = t("fieldMaxValue", { max: field.validation.max });
            setFormErrors((prev) => ({
              ...prev,
              [opKey]: { ...(prev[opKey] ?? {}), [field.key]: errorMsg },
            }));
            return false;
          }
        }
      }

      // Neo N3 address format validation
      if (field.type === "address" && value) {
        if (!/^N[A-HJ-NP-Za-km-z1-9]{33}$/.test(value as string)) {
          errorMsg = t("invalidAddress");
          setFormErrors((prev) => ({
            ...prev,
            [opKey]: { ...(prev[opKey] ?? {}), [field.key]: errorMsg },
          }));
          return false;
        }
      }

      // Pattern validation (skip for empty optional fields)
      if (field.validation?.pattern && typeof value === "string") {
        if (field.required || value !== "") {
          const regex = new RegExp(field.validation.pattern);
          if (!regex.test(value)) {
            errorMsg = t("fieldInvalidFormat");
            setFormErrors((prev) => ({
              ...prev,
              [opKey]: { ...(prev[opKey] ?? {}), [field.key]: errorMsg },
            }));
            return false;
          }
        }
      }

      return true;
    },
    [t],
  );

  const isFormValid = useCallback(
    (opKey: string): boolean => {
      const op = operations.find((o) => o.key === opKey);
      if (!op?.fields?.length) return true;

      return op.fields.every((field) => {
        if (!field.required) return true;
        const value = formDataRef.current[opKey]?.[field.key];
        return value !== "" && value !== null && value !== undefined;
      });
    },
    [operations],
  );

  const validateOperation = useCallback(
    (op: OperationDefinition): boolean => {
      if (!op.fields?.length) return true;

      let valid = true;
      for (const field of op.fields) {
        if (!validateField(op.key, field)) {
          valid = false;
        }
      }
      return valid;
    },
    [validateField],
  );

  // --------------------------------------------------------------------------
  // Submission
  // --------------------------------------------------------------------------

  const isSubmitting = useCallback(
    (opKey: string): boolean => {
      return submittingOps.has(opKey);
    },
    [submittingOps],
  );

  const submitOperation = useCallback(
    async (op: OperationDefinition) => {
      if (!validateOperation(op)) return;
      if (submittingOps.has(op.key)) return;
      if (!onAction) return;

      setSubmittingOps((prev) => new Set(prev).add(op.key));
      try {
        const data = { ...(formDataRef.current[op.key] ?? {}) };

        // Auto-scale amount fields to Fixed8 (1e8)
        if (scaleAmounts && op.fields) {
          for (const field of op.fields) {
            if (
              field.type === "amount" &&
              data[field.key] !== "" &&
              data[field.key] != null
            ) {
              const num = Number(data[field.key]);
              if (!isNaN(num)) {
                data[field.key] = Math.round(num * 1e8);
              }
            }
          }
        }

        await onAction(op.key, data);
      } finally {
        setSubmittingOps((prev) => {
          const next = new Set(prev);
          next.delete(op.key);
          return next;
        });
      }
    },
    [onAction, scaleAmounts, submittingOps, validateOperation],
  );

  // --------------------------------------------------------------------------
  // Render
  // --------------------------------------------------------------------------

  return (
    <div className="operation-panels">
      {operationGroups.primary.length > 1 && (
        <div
          className="operation-tabs"
          role="tablist"
          aria-label={t("operationsPanel")}
        >
          {operationGroups.primary.map((operation) => (
            <button
              key={operation.key}
              type="button"
              role="tab"
              aria-selected={activeOperation?.key === operation.key}
              className={`operation-tab${activeOperation?.key === operation.key ? " operation-tab--active" : ""}`}
              onClick={() => setActiveOperationKey(operation.key)}
            >
              {resolveTitle(operation)}
            </button>
          ))}
        </div>
      )}

      {activeOperation && renderOperationCard(activeOperation)}

      {operationGroups.secondary.length > 0 && (
        <details className="operation-secondary">
          <summary>
            <span>
              {resolveStaticLabel("advancedOperations", "Advanced / Operator")}
            </span>
            <small>{operationGroups.secondary.length}</small>
          </summary>
          <div className="operation-secondary__grid">
            {operationGroups.secondary.map((operation) => (
              <button
                key={operation.key}
                type="button"
                className={`operation-secondary__button${activeOperation?.key === operation.key ? " operation-secondary__button--active" : ""}`}
                onClick={() => setActiveOperationKey(operation.key)}
              >
                {resolveTitle(operation)}
              </button>
            ))}
          </div>
        </details>
      )}
    </div>
  );

  // --------------------------------------------------------------------------
  // Field Renderers
  // --------------------------------------------------------------------------

  function renderField(opKey: string, field: OperationFieldDefinition) {
    if (field.hidden) return null;
    const value = formData[opKey]?.[field.key] ?? "";
    const error = getFieldError(opKey, field.key);
    const label = resolveFieldLabel(field);

    switch (field.type) {
      case "amount":
        return renderInput(opKey, field, {
          type: "number",
          label,
          placeholder: field.placeholder ?? "0.00",
          min: field.validation?.min?.toString(),
          max: field.validation?.max?.toString(),
          suffix: "GAS",
          error,
          value,
        });

      case "address":
        return renderInput(opKey, field, {
          type: "text",
          label,
          placeholder: field.placeholder ?? "N...",
          suffixIcon: "wallet",
          error,
          value,
        });

      case "number":
        return renderInput(opKey, field, {
          type: "number",
          label,
          placeholder: field.placeholder ?? "0",
          min: field.validation?.min?.toString(),
          max: field.validation?.max?.toString(),
          error,
          value,
        });

      case "text":
        return renderInput(opKey, field, {
          type: "text",
          label,
          placeholder: field.placeholder ?? "",
          error,
          value,
        });

      case "select":
        return (
          <div className="field-select">
            {label && <label className="field-label">{label}</label>}
            <select
              className="neo-select"
              value={String(value)}
              required={field.required}
              aria-label={label || field.key}
              onChange={(e) => setFieldValue(opKey, field.key, e.target.value)}
            >
              <option value="" disabled>
                {field.placeholder || t("select")}
              </option>
              {(field.options ?? []).map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.labelKey ? t(opt.labelKey) : (opt.label ?? opt.value)}
                </option>
              ))}
            </select>
          </div>
        );

      case "toggle":
        return (
          <div className="field-toggle">
            <label className="toggle-label">
              <input
                type="checkbox"
                className="toggle-input"
                checked={Boolean(value)}
                aria-label={label || field.key}
                onChange={(e) =>
                  setFieldValue(opKey, field.key, e.target.checked)
                }
              />
              <span className="toggle-switch" />
              {label && <span className="toggle-text">{label}</span>}
            </label>
          </div>
        );

      default:
        return null;
    }
  }

  function renderInput(
    opKey: string,
    field: OperationFieldDefinition,
    config: {
      type: string;
      label?: string;
      placeholder?: string;
      min?: string;
      max?: string;
      suffix?: string;
      suffixIcon?: string;
      error?: string;
      value: unknown;
    },
  ) {
    const inputId = `op-${opKey}-${field.key}`;
    return (
      <div className={`neo-input${config.error ? " neo-input--error" : ""}`}>
        {config.label && (
          <span id={`${inputId}-label`} className="neo-input__label">
            {config.label}
          </span>
        )}
        <div className="neo-input__wrapper">
          <input
            id={inputId}
            type={config.type}
            className="neo-input__field"
            value={String(config.value ?? "")}
            placeholder={config.placeholder}
            required={field.required}
            min={config.min}
            max={config.max}
            aria-label={config.label || field.key}
            aria-labelledby={config.label ? `${inputId}-label` : undefined}
            aria-describedby={config.error ? `${inputId}-error` : undefined}
            aria-invalid={config.error ? true : undefined}
            aria-required={field.required || undefined}
            onChange={(e) => setFieldValue(opKey, field.key, e.target.value)}
          />
          {(config.suffixIcon || config.suffix) && (
            <div className="neo-input__suffix">
              {config.suffix && <span>{config.suffix}</span>}
            </div>
          )}
        </div>
        {config.error && (
          <span
            id={`${inputId}-error`}
            className="neo-input__error"
            role="alert"
            aria-live="assertive"
          >
            {config.error}
          </span>
        )}
      </div>
    );
  }

  function renderOperationCard(operation: OperationDefinition) {
    const visibleFields =
      operation.fields?.filter((field) => !field.hidden) ?? [];

    return (
      <div
        key={operation.key}
        className="neo-card neo-card--erobo operation-card"
      >
        <div className="neo-card__header">
          <span className="neo-card__title">{resolveTitle(operation)}</span>
        </div>
        <div className="neo-card__body">
          {resolveDescription(operation) && (
            <p className="operation-description">
              {resolveDescription(operation)}
            </p>
          )}

          {visibleFields.length > 0 && (
            <div className="operation-fields">
              {visibleFields.map((field) => (
                <div key={field.key} className="operation-field">
                  {renderField(operation.key, field)}
                </div>
              ))}
            </div>
          )}

          {hasStateSummary(operation) && (
            <div className="operation-summary">
              {getOperationStats(operation).map((stat) => (
                <div key={stat.key} className="summary-row">
                  <span className="summary-label">{stat.label}</span>
                  <span className="summary-value">{stat.value}</span>
                </div>
              ))}
            </div>
          )}

          {resolveActionLabel(operation) && (
            <button
              type="button"
              className={`neo-btn neo-btn--primary neo-btn--lg neo-btn--block operation-action-btn${isSubmitting(operation.key) ? " neo-btn--loading" : ""}`}
              disabled={
                isSubmitting(operation.key) || !isFormValid(operation.key)
              }
              aria-label={resolveActionLabel(operation)}
              aria-busy={isSubmitting(operation.key)}
              onClick={() => submitOperation(operation)}
            >
              {isSubmitting(operation.key) ? (
                <div className="neo-btn__spinner" aria-hidden="true" />
              ) : (
                resolveActionLabel(operation)
              )}
            </button>
          )}
        </div>
      </div>
    );
  }

  function resolveStaticLabel(key: string, fallback: string) {
    const label = t(key);
    return label && label !== key ? label : fallback;
  }
}

function splitOperations(operations: OperationDefinition[]) {
  if (operations.length <= 1) {
    return { primary: operations, secondary: [] as OperationDefinition[] };
  }

  const primary = operations.filter((operation, index) => {
    if (
      operation.priority === "secondary" ||
      operation.priority === "operator"
    ) {
      return false;
    }
    if (operation.priority === "primary") return true;
    if (index === 0) return true;
    const text =
      `${operation.key} ${operation.actionMethod ?? ""}`.toLowerCase();
    return /claim|stake|withdraw|open|pay/.test(text);
  });
  const safePrimary = primary.length > 0 ? primary : [operations[0]];
  const secondary = operations.filter(
    (operation) => !safePrimary.includes(operation),
  );
  return { primary: safePrimary, secondary };
}

export default MiniAppOperationPanel;
