// apps/shared/components/ScrollReveal.tsx
import { useRef, useState, useEffect, type ReactNode } from "react";
import { useI18n } from "@shared/react";
import "./ScrollReveal.scss";

export interface ScrollRevealProps {
  animation?: "fade-up" | "fade-down" | "scale-in" | "slide-left" | "slide-right";
  delay?: number;
  duration?: number;
  threshold?: number;
  offset?: number;
  reversible?: boolean;
  ariaLabel?: string;
  className?: string;
  children?: ReactNode;
}

export function ScrollReveal({
  animation = "fade-up",
  delay = 0,
  duration = 800,
  threshold = 0.1,
  offset = -50,
  reversible = false,
  ariaLabel,
  className,
  children,
}: ScrollRevealProps) {
  const { t } = useI18n();
  const ref = useRef<HTMLDivElement>(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    // Failsafe: ensure content shows up eventually
    const failsafe = setTimeout(() => {
      setIsVisible((v) => v || true);
    }, 600);

    // Use standard IntersectionObserver
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (!entry) return;
        if (entry.isIntersecting) {
          setIsVisible(true);
          if (!reversible) observer.disconnect();
        } else if (reversible) {
          setIsVisible(false);
        }
      },
      {
        threshold,
        rootMargin: `0px 0px ${offset}px 0px`,
      },
    );

    observer.observe(el);

    return () => {
      clearTimeout(failsafe);
      observer.disconnect();
    };
  }, [threshold, offset, reversible]);

  const classes = [
    "scroll-reveal",
    animation,
    isVisible && "is-visible",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div
      ref={ref}
      className={classes}
      style={{ transitionDelay: `${delay}ms`, transitionDuration: `${duration}ms` }}
      role="region"
      aria-label={ariaLabel || t("scrollRevealAriaLabel")}
    >
      {children}
    </div>
  );
}

export default ScrollReveal;

// apps/shared/components/ScrollReveal.vue
<template>
  <div
    class="scroll-reveal"
    :class="[animation, { 'is-visible': isVisible }]"
    :style="{ transitionDelay: delay + 'ms', transitionDuration: duration + 'ms' }"
    role="region"
    :aria-label="ariaLabel || t('scrollRevealAriaLabel')"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, getCurrentInstance, onUnmounted } from "vue";
import { useI18n } from "@shared/composables";

interface Props {
  animation?: "fade-up" | "fade-down" | "scale-in" | "slide-left" | "slide-right";
  delay?: number;
  duration?: number;
  threshold?: number;
  offset?: number;
  reversible?: boolean;
  ariaLabel?: string;
}

const { t } = useI18n();

const props = withDefaults(defineProps<Props>(), {
  animation: "fade-up",
  delay: 0,
  duration: 800,
  threshold: 0.1,
  offset: -50,
  reversible: false,
  ariaLabel: undefined,
});

const isVisible = ref(false);
const instance = getCurrentInstance();
let observer: ReturnType<typeof uni.createIntersectionObserver> | null = null;
let outerTimer: ReturnType<typeof setTimeout> | undefined;
let innerTimer: ReturnType<typeof setTimeout> | undefined;

onMounted(() => {
  // Small delay to ensure DOM is ready
  outerTimer = setTimeout(() => {
    if (!instance) return;

    // Failsafe: Ensure content shows up eventually if observer fails
    innerTimer = setTimeout(() => {
      if (!isVisible.value) {
        isVisible.value = true;
      }
    }, 500);

    observer = uni.createIntersectionObserver(instance);

    observer
      .relativeToViewport({ bottom: props.offset })
      .observe(".scroll-reveal", (res: { intersectionRatio: number }) => {
        if (res.intersectionRatio > 0) {
          isVisible.value = true;
          // Only disconnect if not reversible
          if (!props.reversible) {
            observer.disconnect();
          }
        } else {
          if (props.reversible) {
            isVisible.value = false;
          }
        }
      });
  }, 100);
});

defineExpose({ isVisible });

onUnmounted(() => {
  if (outerTimer !== undefined) {
    clearTimeout(outerTimer);
    outerTimer = undefined;
  }
  if (innerTimer !== undefined) {
    clearTimeout(innerTimer);
    innerTimer = undefined;
  }
  if (observer) {
    observer.disconnect();
    observer = null;
  }
});
</script>

<style lang="scss" scoped>
.scroll-reveal {
  opacity: 0;
  transition-property: opacity, transform;
  transition-timing-function: cubic-bezier(0.16, 1, 0.3, 1); // Smooth "Out Expo"ish
  will-change: opacity, transform;

  // Animation Variants
  &.fade-up {
    transform: translateY(40px);
  }

  &.fade-down {
    transform: translateY(-40px);
  }

  &.scale-in {
    transform: scale(0.92);
  }

  &.slide-left {
    transform: translateX(40px);
  }

  &.slide-right {
    transform: translateX(-40px);
  }

  // Active State
  &.is-visible {
    opacity: 1;
    transform: translate(0, 0) scale(1);
  }
}

// Disable scroll animations for users who prefer reduced motion
@media (prefers-reduced-motion: reduce) {
  .scroll-reveal {
    opacity: 1 !important;
    transform: none !important;
    transition: none !important;
  }
}
</style>
