// apps/gov-merc/src/components/MercActionCards.vue
<template>
  <!-- Deposit Card -->
  <NeoCard class="mb-6" variant="erobo">
    <div class="form-group-neo">
      <NeoInput v-model="localDepositAmount" type="number" :placeholder="t('enterAmount')" :suffix="t('tokenNeo')" :label="t('depositAmount')" :min="0" />
      <NeoButton type="button" variant="primary" size="lg" block :loading="isBusy" @click="handleDeposit">
        {{ t("depositNeo") }}
      </NeoButton>
    </div>
  </NeoCard>

  <!-- Withdraw Card -->
  <NeoCard class="mb-6" variant="erobo">
    <div class="form-group-neo">
      <NeoInput v-model="localWithdrawAmount" type="number" :placeholder="t('enterAmount')" :suffix="t('tokenNeo')" :label="t('withdrawAmount')" :min="0" />
      <NeoButton type="button" variant="secondary" size="lg" block :loading="isBusy" @click="handleWithdraw">
        {{ t("withdrawNeo") }}
      </NeoButton>
    </div>
  </NeoCard>

  <!-- Bid Card -->
  <NeoCard variant="erobo" :title="t('placeBid')" class="mb-6">
    <div class="form-group-neo">
      <NeoInput v-model="localBidAmount" type="number" :placeholder="t('enterAmount')" :suffix="t('tokenGas')" :label="t('bidAmount')" :min="0" />
      <NeoButton type="button" variant="primary" size="lg" block :loading="isBusy" @click="handleBid">
        {{ t("placeBid") }}
      </NeoButton>
    </div>
  </NeoCard>
</template>

<script setup lang="ts">
import { ref, watch, inject } from "vue";
import type { Ref } from "vue";
import { NeoCard, NeoInput, NeoButton } from "@shared/components";
import { MINIAPP_ACTIONS_KEY } from "@shared/utils/defineMiniApp";

const props = defineProps<{
  t: (key: string, params?: Record<string, string | number>) => string;
  isBusy: boolean;
  depositAmountRef: Ref<string> | undefined;
  withdrawAmountRef: Ref<string> | undefined;
  bidAmountRef: Ref<string> | undefined;
}>();

const actions = inject(MINIAPP_ACTIONS_KEY, new Map());

// Local form state synced to composable refs
const localDepositAmount = ref("");
const localWithdrawAmount = ref("");
const localBidAmount = ref("");

watch(localDepositAmount, (val) => {
  if (props.depositAmountRef) props.depositAmountRef.value = val;
});
watch(localWithdrawAmount, (val) => {
  if (props.withdrawAmountRef) props.withdrawAmountRef.value = val;
});
watch(localBidAmount, (val) => {
  if (props.bidAmountRef) props.bidAmountRef.value = val;
});

const handleDeposit = async () => {
  const handler = actions.get("depositNeo");
  if (handler) {
    await handler();
    localDepositAmount.value = "";
  }
};

const handleWithdraw = async () => {
  const handler = actions.get("withdrawNeo");
  if (handler) {
    await handler();
    localWithdrawAmount.value = "";
  }
};

const handleBid = async () => {
  const handler = actions.get("placeBid");
  if (handler) {
    await handler();
    localBidAmount.value = "";
  }
};
</script>

<style lang="scss" scoped>
@use "@shared/styles/tokens.scss" as *;
@use "@shared/styles/variables.scss" as *;
@use "../pages/index/gov-merc-theme.scss" as *;

.form-group-neo {
  display: flex;
  flex-direction: column;
  gap: 16px;
}
</style>

// apps/gov-merc/src/components/MercActionCards.tsx
import { NeoButton, NeoInput } from "@shared/components-react";
import "./MercActionCards.scss";

export type AmountField = "depositAmount" | "withdrawAmount" | "bidAmount";

interface MercActionCardsProps {
  t: (key: string, params?: Record<string, string | number>) => string;
  isBusy: boolean;
  depositAmount: string;
  withdrawAmount: string;
  bidAmount: string;
  onAmountChange: (key: AmountField, value: string) => void;
  dispatch: (name: string, ...args: unknown[]) => Promise<void>;
}

function isPositiveAmount(value: string) {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0;
}

export default function MercActionCards({
  t,
  isBusy,
  depositAmount,
  withdrawAmount,
  bidAmount,
  onAmountChange,
  dispatch,
}: MercActionCardsProps) {
  return (
    <>
      <div className="gov-merc-action-card">
        <div>
          <span>{t("depositNeo")}</span>
          <p>{t("actionDepositHint")}</p>
        </div>
        <NeoInput
          value={depositAmount}
          type="number"
          min={0}
          suffix="NEO"
          placeholder={t("enterAmount")}
          label={t("depositAmount")}
          onChange={(value) => onAmountChange("depositAmount", value)}
        />
        <NeoButton
          variant="primary"
          loading={isBusy}
          disabled={isBusy || !isPositiveAmount(depositAmount)}
          onClick={() => dispatch("depositNeo")}
        >
          {t("depositNeo")}
        </NeoButton>
      </div>

      <div className="gov-merc-action-card">
        <div>
          <span>{t("withdrawNeo")}</span>
          <p>{t("actionWithdrawHint")}</p>
        </div>
        <NeoInput
          value={withdrawAmount}
          type="number"
          min={0}
          suffix="NEO"
          placeholder={t("enterAmount")}
          label={t("withdrawAmount")}
          onChange={(value) => onAmountChange("withdrawAmount", value)}
        />
        <NeoButton
          variant="secondary"
          loading={isBusy}
          disabled={isBusy || !isPositiveAmount(withdrawAmount)}
          onClick={() => dispatch("withdrawNeo")}
        >
          {t("withdrawNeo")}
        </NeoButton>
      </div>

      <div className="gov-merc-action-card">
        <div>
          <span>{t("placeBid")}</span>
          <p>{t("actionBidHint")}</p>
        </div>
        <NeoInput
          value={bidAmount}
          type="number"
          min={0}
          suffix="GAS"
          placeholder={t("enterAmount")}
          label={t("bidAmount")}
          onChange={(value) => onAmountChange("bidAmount", value)}
        />
        <NeoButton
          variant="primary"
          loading={isBusy}
          disabled={isBusy || !isPositiveAmount(bidAmount)}
          onClick={() => dispatch("placeBid")}
        >
          {t("placeBid")}
        </NeoButton>
      </div>
    </>
  );
}
