// apps/quadratic-funding/src/pages/index/components/RoundForm.vue
<template>
  <FormCard
    :submit-label="isLoading ? t('creatingRound') : t('createRound')"
    :submit-loading="isLoading"
    :submit-disabled="isLoading"
    @submit="emitCreate"
  >
    <NeoInput v-model="localForm.title" :label="t('roundTitle')" :placeholder="t('roundTitlePlaceholder')" />
    <NeoInput
      v-model="localForm.description"
      type="textarea"
      :label="t('roundDescription')"
      :placeholder="t('roundDescriptionPlaceholder')"
    />

    <div class="input-group">
      <span class="input-label">{{ t("assetType") }}</span>
      <div class="asset-toggle">
        <NeoButton size="sm" variant="primary" disabled>
          {{ t("assetGas") }}
        </NeoButton>
      </div>
    </div>

    <NeoInput
      v-model="localForm.matchingPool"
      type="number"
      :label="t('matchingPool')"
      :placeholder="t('matchingPoolPlaceholder')"
      :suffix="t('tokenGas')"
      :hint="t('matchingPoolHint')"
    />

    <NeoInput v-model="localForm.startTime" :label="t('roundStart')" :placeholder="t('roundStartPlaceholder')" />
    <NeoInput v-model="localForm.endTime" :label="t('roundEnd')" :placeholder="t('roundEndPlaceholder')" />
  </FormCard>
</template>

<script setup lang="ts">
import { reactive, ref } from "vue";
import { NeoInput, NeoButton, FormCard } from "@shared/components";
import { createUseI18n } from "@shared/composables/useI18n";
import { messages } from "@/locale/messages";

const emit = defineEmits<{
  (
    e: "create",
    data: {
      title: string;
      description: string;
      asset: string;
      matchingPool: string;
      startTime: string;
      endTime: string;
    }
  ): void;
}>();

const { t } = createUseI18n(messages)();
const isLoading = ref(false);

const localForm = reactive({
  title: "",
  description: "",
  asset: "GAS",
  matchingPool: "",
  startTime: "",
  endTime: "",
});

const emitCreate = () => {
  emit("create", { ...localForm });
};

defineExpose({
  setLoading: (loading: boolean) => {
    isLoading.value = loading;
  },
  reset: () => {
    localForm.title = "";
    localForm.description = "";
    localForm.matchingPool = "";
    localForm.startTime = "";
    localForm.endTime = "";
  },
});
</script>

<style lang="scss" scoped>
@use "@shared/styles/mixins.scss" as *;

.input-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.input-label {
  @include stat-label;
  letter-spacing: 0.05em;
  color: var(--qf-muted);
}

.asset-toggle {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}
</style>

// apps/quadratic-funding/src/pages/index/components/RoundForm.tsx
import { useState } from "react";
import { NeoCard, NeoInput, NeoButton } from "@shared/components-react";

interface RoundFormProps {
  onSubmit: (...args: unknown[]) => void;
  t: (key: string) => string;
}

export default function RoundForm({ onSubmit, t }: RoundFormProps) {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [matchingPool, setMatchingPool] = useState("");
  const [startTime, setStartTime] = useState("");
  const [endTime, setEndTime] = useState("");

  return (
    <NeoCard title={t("createRound")} className="qf-form-panel">
      <p className="qf-panel-hint">{t("matchingPoolHint")}</p>
      <div className="qf-form-grid">
        <NeoInput
          value={title}
          label={t("roundTitle")}
          placeholder={t("roundTitlePlaceholder")}
          onChange={setTitle}
        />
        <NeoInput
          value={matchingPool}
          type="number"
          label={t("matchingPool")}
          placeholder={t("matchingPoolPlaceholder")}
          onChange={setMatchingPool}
        />
        <NeoInput
          value={startTime}
          label={t("roundStart")}
          placeholder={t("roundStartPlaceholder")}
          onChange={setStartTime}
        />
        <NeoInput
          value={endTime}
          label={t("roundEnd")}
          placeholder={t("roundEndPlaceholder")}
          onChange={setEndTime}
        />
      </div>
      <NeoInput
        value={description}
        type="textarea"
        label={t("roundDescription")}
        placeholder={t("roundDescriptionPlaceholder")}
        onChange={setDescription}
      />
      <div className="qf-panel-footer">
        <NeoButton
          variant="primary"
          onClick={() =>
            onSubmit({
              title,
              description,
              asset: "GAS",
              matchingPool,
              startTime,
              endTime,
            })
          }
        >
          {t("createRound")}
        </NeoButton>
      </div>
    </NeoCard>
  );
}
