// apps/quadratic-funding/src/pages/index/components/RoundAdminPanel.vue
<template>
  <NeoCard variant="erobo-neo" class="admin-card">
    <div class="admin-header">
      <span class="section-title">{{ t("adminTools") }}</span>
      <span class="admin-subtitle">#{{ round.id }} · {{ round.assetSymbol }}</span>
    </div>

    <div class="form-group">
      <NeoInput
        v-model="matchingAmount"
        type="number"
        :label="t('addMatching')"
        :placeholder="t('addMatchingPlaceholder')"
        :suffix="round.assetSymbol"
      />
      <NeoButton
        size="sm"
        variant="secondary"
        type="button"
        :loading="isAddingMatching"
        :disabled="!canManage"
        @click="emitAddMatching"
      >
        {{ isAddingMatching ? t("addingMatching") : t("addMatching") }}
      </NeoButton>
    </div>

    <div class="admin-divider" />

    <div class="form-group">
      <NeoInput
        v-model="projectIds"
        :label="t('finalizeProjectsJson')"
        :placeholder="t('finalizeProjectsPlaceholder')"
      />
      <NeoInput
        v-model="matchedAmounts"
        :label="t('finalizeMatchesJson')"
        :placeholder="t('finalizeMatchesPlaceholder')"
      />
      <span class="hint-text">{{ t("finalizeHint") }}</span>
      <NeoButton
        size="sm"
        variant="primary"
        type="button"
        :loading="isFinalizing"
        :disabled="!canFinalize"
        @click="emitFinalize"
      >
        {{ isFinalizing ? t("finalizing") : t("finalizeRound") }}
      </NeoButton>
    </div>

    <div class="admin-divider" />

    <NeoButton
      size="sm"
      variant="secondary"
      type="button"
      :loading="isClaimingUnused"
      :disabled="!canClaimUnused"
      @click="emitClaimUnused"
    >
      {{ isClaimingUnused ? t("claimingUnused") : t("claimUnused") }}
    </NeoButton>
  </NeoCard>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { NeoInput, NeoButton, NeoCard } from "@shared/components";
import { createUseI18n } from "@shared/composables/useI18n";
import { messages } from "@/locale/messages";
import type { RoundItem } from "./RoundList.vue";

const props = defineProps<{
  round: RoundItem;
  canManage: boolean;
  canFinalize: boolean;
  canClaimUnused: boolean;
  isAddingMatching: boolean;
  isFinalizing: boolean;
  isClaimingUnused: boolean;
}>();

const emit = defineEmits<{
  (e: "addMatching", amount: string): void;
  (e: "finalize", projectIds: string, matchedAmounts: string): void;
  (e: "claimUnused"): void;
}>();

const { t } = createUseI18n(messages)();
const matchingAmount = ref("");
const projectIds = ref("");
const matchedAmounts = ref("");

const emitAddMatching = () => emit("addMatching", matchingAmount.value);
const emitFinalize = () => emit("finalize", projectIds.value, matchedAmounts.value);
const emitClaimUnused = () => emit("claimUnused");
</script>

<style lang="scss" scoped>
.admin-card {
  background: var(--qf-card-bg);
  border: 1px solid var(--qf-card-border);
  border-radius: 18px;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.admin-header {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 12px;
}

.section-title {
  font-size: 18px;
  font-weight: 700;
}

.admin-subtitle {
  font-size: 11px;
  color: var(--qf-muted);
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.admin-divider {
  height: 1px;
  background: rgba(255, 255, 255, 0.08);
  margin: 6px 0;
}

.hint-text {
  font-size: 11px;
  color: var(--qf-muted);
}
</style>

// apps/quadratic-funding/src/pages/index/components/RoundAdminPanel.tsx
import { useState } from "react";
import { NeoInput, NeoButton, NeoCard } from "@shared/components-react";

interface RoundAdminPanelProps {
  round: Record<string, unknown>; canManage: boolean; canFinalize: boolean; canClaimUnused: boolean;
  isAddingMatching: boolean; isFinalizing: boolean; isClaimingUnused: boolean;
  /** IDs of projects registered in the selected round, for finalize guidance. */
  knownProjectIds?: string[];
  onAddMatching: (...args: unknown[]) => void; onFinalize: (...args: unknown[]) => void; onClaimUnused: () => void;
  t: (key: string) => string;
}

export default function RoundAdminPanel({ round, canManage, canFinalize, canClaimUnused, isAddingMatching, isFinalizing, isClaimingUnused, knownProjectIds: knownProjectIdList = [], onAddMatching, onFinalize, onClaimUnused, t }: RoundAdminPanelProps) {
  const [matchingAmount, setMatchingAmount] = useState("");
  const [projectIds, setProjectIds] = useState("");
  const [matchedAmounts, setMatchedAmounts] = useState("");

  const knownProjectIds = knownProjectIdList.join(", ");

  const prefillProjectIds = () => {
    if (knownProjectIdList.length === 0) return;
    setProjectIds(JSON.stringify(knownProjectIdList.map((id) => Number.parseInt(id, 10))));
  };

  return (
    <NeoCard title={t("adminTools")} className="qf-admin-panel">
      <div className="qf-admin-group">
        <p className="qf-admin-group-title">{t("addMatching")}</p>
        <NeoInput value={matchingAmount} type="number" label={t("addMatching")} onChange={setMatchingAmount} />
        <NeoButton size="sm" variant="secondary" loading={isAddingMatching} disabled={!canManage} onClick={() => onAddMatching(matchingAmount)}>{t("addMatching")}</NeoButton>
      </div>
      <div className="qf-admin-group">
        <p className="qf-admin-group-title">{t("finalizeRound")}</p>
        <NeoInput value={projectIds} label={t("finalizeProjectsJson")} placeholder={t("finalizeProjectsPlaceholder")} onChange={setProjectIds} />
        <NeoInput value={matchedAmounts} label={t("finalizeMatchesJson")} placeholder={t("finalizeMatchesPlaceholder")} hint={t("finalizeHint")} onChange={setMatchedAmounts} />
        {knownProjectIds ? (
          <p className="qf-finalize-hint">
            {t("finalizeKnownProjects")}: <b>{knownProjectIds}</b>{" "}
            <button type="button" className="qf-finalize-prefill" onClick={prefillProjectIds}>
              {t("finalizePrefill")}
            </button>
          </p>
        ) : null}
        <NeoButton size="sm" variant="primary" loading={isFinalizing} disabled={!canFinalize} onClick={() => onFinalize(projectIds, matchedAmounts)}>{t("finalizeRound")}</NeoButton>
      </div>
      <div className="qf-admin-group">
        <p className="qf-admin-group-title">{t("claimUnused")}</p>
        <NeoButton size="sm" variant="secondary" loading={isClaimingUnused} disabled={!canClaimUnused} onClick={onClaimUnused}>{t("claimUnused")}</NeoButton>
      </div>
    </NeoCard>
  );
}
