// apps/quadratic-funding/src/pages/index/components/RoundList.vue
<template>
  <NeoCard variant="erobo" class="round-list">
    <div class="rounds-header">
      <span class="section-title">{{ t("roundsTitle") }}</span>
      <NeoButton size="sm" variant="secondary" :loading="isRefreshing" @click="emitRefresh">
        {{ t("refresh") }}
      </NeoButton>
    </div>

    <ItemList
      :items="rounds as unknown as Record<string, unknown>[]"
      item-key="id"
      :empty-text="t('emptyRounds')"
      :aria-label="t('ariaRounds')"
    >
      <template #empty>
        <NeoCard variant="erobo" class="p-6 text-center opacity-70">
          <span class="text-xs">{{ t("emptyRounds") }}</span>
        </NeoCard>
      </template>
      <template #item="{ item }">
        <div class="round-card">
          <div class="round-card__header">
            <div>
              <span class="round-title">{{
                (item as unknown as RoundItem).title || `#${(item as unknown as RoundItem).id}`
              }}</span>
              <span class="round-subtitle"
                >#{{ (item as unknown as RoundItem).id }} · {{ (item as unknown as RoundItem).assetSymbol }}</span
          >
            </div>
            <span :class="['status-pill', (item as unknown as RoundItem).status]">{{
              roundStatusLabel((item as unknown as RoundItem).status)
            }}</span>
          </div>

          <span class="round-desc">{{ (item as unknown as RoundItem).description || "--" }}</span>

          <div class="round-metrics">
            <div>
              <span class="metric-label">{{ t("matchingPool") }}</span>
              <span class="metric-value"
                >{{
                  formatAmount((item as unknown as RoundItem).assetSymbol, (item as unknown as RoundItem).matchingPool)
                }}
                {{ (item as unknown as RoundItem).assetSymbol }}</span
          >
            </div>
            <div>
              <span class="metric-label">{{ t("matchingRemaining") }}</span>
              <span class="metric-value"
                >{{
                  formatAmount(
                    (item as unknown as RoundItem).assetSymbol,
                    (item as unknown as RoundItem).matchingRemaining
                  )
                }}
                {{ (item as unknown as RoundItem).assetSymbol }}</span
          >
            </div>
            <div>
              <span class="metric-label">{{ t("totalContributed") }}</span>
              <span class="metric-value"
                >{{
                  formatAmount(
                    (item as unknown as RoundItem).assetSymbol,
                    (item as unknown as RoundItem).totalContributed
                  )
                }}
                {{ (item as unknown as RoundItem).assetSymbol }}</span
          >
            </div>
            <div>
              <span class="metric-label">{{ t("projectCount") }}</span>
              <span class="metric-value">{{ (item as unknown as RoundItem).projectCount.toString() }}</span>
            </div>
          </div>

          <div class="round-meta">
            <span class="meta-item"
              >{{ t("roundSchedule") }}:
              {{
                formatSchedule((item as unknown as RoundItem).startTime, (item as unknown as RoundItem).endTime)
              }}</span
          >
            <span class="meta-item"
              >{{ t("roundCreator") }}: {{ formatAddress((item as unknown as RoundItem).creator) }}</span
          >
          </div>

          <div class="round-actions">
            <NeoButton size="sm" variant="secondary" @click="emitSelect(item as unknown as RoundItem)">
              {{ selectedRoundId === (item as unknown as RoundItem).id ? t("selectedRound") : t("selectRound") }}
            </NeoButton>
          </div>
        </div>
      </template>
    </ItemList>
  </NeoCard>
</template>

<script setup lang="ts">
import { NeoCard, NeoButton, ItemList } from "@shared/components";
import { createUseI18n } from "@shared/composables/useI18n";
import { messages } from "@/locale/messages";

export interface RoundItem {
  id: string;
  creator: string;
  assetSymbol: string;
  matchingPool: bigint;
  matchingRemaining: bigint;
  totalContributed: bigint;
  projectCount: bigint;
  startTime: number;
  endTime: number;
  status: string;
  title: string;
  description: string;
}

const props = defineProps<{
  rounds: RoundItem[];
  selectedRoundId: string;
  isRefreshing: boolean;
  roundStatusLabel: (status: string) => string;
  formatAmount: (symbol: string, amount: bigint) => string;
  formatSchedule: (start: number, end: number) => string;
  formatAddress: (addr: string) => string;
}>();

const emit = defineEmits<{
  (e: "refresh"): void;
  (e: "select", round: RoundItem): void;
}>();

const { t } = createUseI18n(messages)();

const emitRefresh = () => emit("refresh");
</script>

<style lang="scss" scoped>
@use "@shared/styles/mixins.scss" as *;

.round-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.rounds-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.section-title {
  font-size: 18px;
  font-weight: 700;
}

.round-cards {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.round-card {
  background: var(--qf-card-bg);
  border: 1px solid var(--qf-card-border);
  border-radius: 18px;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.round-card__header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
}

.round-title {
  font-size: 15px;
  font-weight: 700;
}

.round-subtitle {
  display: block;
  font-size: 11px;
  color: var(--qf-muted);
  margin-top: 2px;
}

.round-desc {
  font-size: 12px;
  color: var(--qf-muted);
  line-height: 1.5;
}

.round-metrics {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(130px, 1fr));
  gap: 12px;
}

.metric-label {
  @include stat-label;
  font-size: 10px;
  color: var(--qf-muted);
  letter-spacing: 0.08em;
}

.metric-value {
  font-size: 15px;
  font-weight: 700;
  color: var(--qf-accent-strong);
}

.round-meta {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.meta-item {
  font-size: 11px;
  color: var(--qf-muted);
}

.round-actions {
  display: flex;
  gap: 10px;
}

.status-pill {
  padding: 4px 10px;
  border-radius: 999px;
  font-size: 10px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  background: rgba(20, 184, 166, 0.2);
  color: var(--qf-accent);
}

.status-pill.upcoming {
  background: rgba(59, 130, 246, 0.2);
  color: var(--qf-info);
}

.status-pill.ended {
  background: rgba(251, 191, 36, 0.2);
  color: var(--qf-warn);
}

.status-pill.finalized {
  background: rgba(34, 197, 94, 0.2);
  color: var(--qf-success);
}

.status-pill.cancelled {
  background: rgba(239, 68, 68, 0.2);
  color: var(--qf-danger);
}

.empty-state {
  margin-top: 10px;
}
</style>

// apps/quadratic-funding/src/pages/index/components/RoundList.tsx
import { NeoCard, NeoButton } from "@shared/components-react";

export interface RoundItem {
  id: string;
  creator: string;
  assetSymbol: string;
  matchingPool: bigint;
  matchingRemaining: bigint;
  totalContributed: bigint;
  projectCount: bigint;
  startTime: number;
  endTime: number;
  status: string;
  title: string;
  description: string;
  finalized?: boolean;
  cancelled?: boolean;
}

interface RoundListProps {
  rounds: Array<Record<string, unknown>>;
  selectedRoundId: string;
  isRefreshing: boolean;
  roundStatusLabel: (round: Record<string, unknown>) => string;
  formatAmount: (v: unknown) => string;
  formatSchedule: (v: unknown) => string;
  formatAddress: (addr: string) => string;
  onRefresh: () => void;
  onSelect: (round: Record<string, unknown>) => void;
  t: (key: string) => string;
}

export default function RoundList({
  rounds,
  selectedRoundId,
  isRefreshing,
  roundStatusLabel,
  formatAmount,
  formatSchedule,
  formatAddress,
  onRefresh,
  onSelect,
  t,
}: RoundListProps) {
  return (
    <NeoCard
      title={t("roundsTitle")}
      className="qf-round-panel"
      header={
        <NeoButton size="sm" variant="secondary" disabled={isRefreshing} onClick={onRefresh}>
          {t("refresh")}
        </NeoButton>
      }
    >
      {rounds.length === 0 ? (
        <div className="qf-empty-ledger">
          <strong>{t("qfNoRoundTitle")}</strong>
          <span>{t("qfNoRoundBody")}</span>
        </div>
      ) : (
        <div className="qf-round-list">
          {rounds.map((round) => {
            const isSelected = selectedRoundId === String(round.id);
            return (
              <button
                key={String(round.id)}
                type="button"
                className={`qf-round-card${isSelected ? " is-selected" : ""}`}
                aria-pressed={isSelected}
                onClick={() => onSelect(round)}
              >
                <span className="qf-round-card-top">
                  <strong>{String(round.title || `#${round.id}`)}</strong>
                  <span className={`qf-status-pill ${String(round.status || "active")}`}>
                    {roundStatusLabel(round)}
                  </span>
                </span>
                <span className="qf-round-card-copy">
                  {String(round.description || t("roundDescriptionPlaceholder"))}
                </span>
                <span className="qf-round-card-grid">
                  <span>
                    <small>{t("matchingRemaining")}</small>
                    <b>{formatAmount(round.matchingRemaining ?? round.matchingPool)}</b>
                  </span>
                  <span>
                    <small>{t("totalContributed")}</small>
                    <b>{formatAmount(round.totalContributed)}</b>
                  </span>
                  <span>
                    <small>{t("roundSchedule")}</small>
                    <b>{formatSchedule(round.startTime)} - {formatSchedule(round.endTime)}</b>
                  </span>
                  <span>
                    <small>{t("roundCreator")}</small>
                    <b>{formatAddress(String(round.creator || ""))}</b>
                  </span>
                </span>
              </button>
            );
          })}
        </div>
      )}
    </NeoCard>
  );
}
